/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2023-01-06 09:59:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.weixin.workflow.searchInfo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.js.oa.weixin.common.util.WorkflowForWeiXinUtil;
import java.util.*;
import java.sql.ResultSet;
import com.js.util.util.DataSourceBase;

public final class search_005finfoAjaxForWeiXin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.js.oa.weixin.common.util.WorkflowForWeiXinUtil");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.js.util.util.DataSourceBase");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n");

request.setCharacterEncoding("utf-8");
int maxPageItems=15;
int recordCount=0;
String pageParameters="customName,type";
String customName =request.getParameter("customName")==null?"":WorkflowForWeiXinUtil.decordStr(request.getParameter("customName"));
String type = request.getParameter("type")==null?"":request.getParameter("type");
String title = "";
int pageOffset = request.getParameter("pager.offset")==null||
		"".equals(request.getParameter("pager.offset"))||
		"null".equals(request.getParameter("pager.offset"))?
		0:Integer.valueOf(request.getParameter("pager.offset"));
DataSourceBase base = new DataSourceBase();
ResultSet rs = null;
List<String[]> list = new ArrayList<String[]>(); 
try{
	base.begin();
	String sql = "SELECT * FROM (SELECT j.jst_3282_f4339,j.jst_3282_f4338,j.jst_3282_f4341,j.jst_3282_f4369,e.EMPNAME,d.DISTRICTNAME,j.jst_3282_f4353"+ 
			" FROM jst_3282 j JOIN org_employee e ON j.jst_3282_f4338=e.EMP_ID "+
			" LEFT JOIN oa_district d ON j.jst_3282_f4341=d.DISTRICT_ID "+
			" WHERE j.jst_3282_f4339 LIKE '%"+customName+"%'"+
			" UNION "+
			" SELECT j.jst_3282_f4345,j.jst_3294_f4556,j.jst_3282_f4341,j.jst_3294_f4555,e.EMPNAME,d.DISTRICTNAME,j.jst_3282_f4352"+ 
			" FROM jst_3294 j JOIN org_employee e ON j.jst_3294_f4556=e.EMP_ID LEFT JOIN oa_district d ON j.jst_3282_f4341=d.DISTRICT_ID"+ 
			" WHERE j.jst_3282_f4345 LIKE '%"+customName+"%') f LIMIT 0,20";
	String recordNum = "SELECT count(*) FROM (SELECT j.jst_3282_f4339"+ 
			" FROM jst_3282 j JOIN org_employee e ON j.jst_3282_f4338=e.EMP_ID "+
			" LEFT JOIN oa_district d ON j.jst_3282_f4341=d.DISTRICT_ID "+
			" WHERE j.jst_3282_f4339 LIKE '%"+customName+"%'"+
			" UNION "+
			" SELECT j.jst_3282_f4345"+ 
			" FROM jst_3294 j JOIN org_employee e ON j.jst_3294_f4556=e.EMP_ID LEFT JOIN oa_district d ON j.jst_3282_f4341=d.DISTRICT_ID"+ 
			" WHERE j.jst_3282_f4345 LIKE '%"+customName+"%') f";

	rs = base.executeQuery(recordNum);
	if(rs.next()){
		recordCount = rs.getInt(1);
	}
	rs.close();
	//recordCount = 33;
	rs = base.executeQuery(sql);
	while(rs.next()){
		String[] info = new String[5];
		String name = rs.getString(1)==null?"&nbsp;":rs.getString(1);
		String cumName = "";
		for(int num=0;num<name.indexOf(customName);num++){
			cumName += "*";
		}
		cumName += "<font color='red'>"+customName+"</font>";
		for(int num=name.indexOf(customName)+customName.length();num<name.length();num++){
			cumName += "*";
		}
		info[0] = cumName;
		info[1] = rs.getString(5)==null?"&nbsp;":rs.getString(5);
		info[2] = rs.getString(6)==null?"&nbsp;":rs.getString(6);
		info[3] = rs.getString(4)==null?"&nbsp;":rs.getString(4);
		info[4] = rs.getString(7)==null?"&nbsp;":rs.getString(7);
		list.add(info);
	}
	base.end();
}catch(Exception e){
	base.end();
	e.printStackTrace();
}

String strString="";

strString+="<DIV style=\"width: 100%;height: 40px;position: fixed;top: 0px;left: 0px;z-index: 9998;padding-top: 5px;background-color: #efefef;text-align: center;\">";
strString+="<FORM id=\"searchForm\" action='' method=\"post\">";
strString+="<INPUT type=\"hidden\" id=\"keyword\" name=\"keyword\" />";
strString+="<INPUT type=\"text\" id=\"keys\" name=\"keys\" style=\"width: 93%;height: 30px;padding-top: 3px;padding-bottom: 3px;padding-left: 10px;border-radius:3px;font-size: 18px;\" value="+customName+" >";
strString+="<DIV id=\"imgDiv\">";
strString+="<IMG onclick=\"showSearchInfo("+customName+");\" style=\"height: 30px;\" alt=\"搜索\" src=\"/jsoa/images/weixin/search.png\" />";
strString+="</DIV>";
strString+="</FORM>";
strString+="</DIV>";
strString+="<DIV style='padding-top: 35px;'>";
strString+="<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" >";
strString+="<tr align=\"center\">";
strString+="<td align='center' height=\"35px\" style='border-right:1px solid #acacac;'>"+customName+"名称</td>";
strString+="<td align='center' height=\"35px\" style='border-right:1px solid #acacac;'>区域</td>";
strString+="<td align='center' height=\"35px\" style='border-right:1px solid #acacac;'>负责人</td>";
strString+="<td align='center' height=\"35px\" style='border-right:1px solid #acacac;'>报备日期</td>";
strString+="</tr>";
String classType = "listTableLine1";
if(list!=null&&list.size()>0){
 for(int i=0;i<list.size();i++){
	if(i%2==1){
		classType = "listTableLine1";
	}else{
		classType = "listTableLine2";
	}
	String[] str = (String[])list.get(i);
	strString+="<tr>";
	strString+="<td  height=\"30px\" style='border-right:1px solid #acacac;' class="+classType+">"+str[0]+"</td>";
	strString+="<td  height=\"30px\" style='border-right:1px solid #acacac;' class="+classType+">"+str[2]+"</td>";
	strString+="<td  height=\"30px\" style='border-right:1px solid #acacac;' class="+classType+">"+str[1]+"</td>";
	strString+="<td  height=\"30px\" style='border-right:1px solid #acacac;' class="+classType+">"+str[3]+"</td>";
	strString+="</tr>";
}
}else{
   strString+="<tr>";
	strString+="<td colspan=4 height=\"30px\" align='center' class="+classType+">暂无数据！</td>";
   strString+="</tr>";
}

strString+="</table>";
strString+="</DIV>";
strString+="<div id=\"searchInforButtons\"></div>";
System.out.println("strString:"+strString);
out.write(strString); 

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
