/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2023-01-06 09:45:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menulist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-nested.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/pager-taglib.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-logic.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-tiles.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/public/page/pager.jsp", Long.valueOf(1499751452000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-html.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-template.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-bean.tld", Long.valueOf(1499751390000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fhtml;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fpager_0026_005furl_005fscope_005fmaxPageItems_005fmaxIndexPages_005fitems_005fisOffset_005findex_005fexport;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fparam_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005findex_0026_005fexport;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fpage;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005ffirst;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fprev;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fpages;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fnext;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005flast_0026_005fexport;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fhtml_005fhtml = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fpager_0026_005furl_005fscope_005fmaxPageItems_005fmaxIndexPages_005fitems_005fisOffset_005findex_005fexport = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fparam_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005findex_0026_005fexport = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fpage = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005ffirst = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fprev = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fpages = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fnext = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005flast_0026_005fexport = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fhtml_005fhtml.release();
    _005fjspx_005ftagPool_005fpg_005fpager_0026_005furl_005fscope_005fmaxPageItems_005fmaxIndexPages_005fitems_005fisOffset_005findex_005fexport.release();
    _005fjspx_005ftagPool_005fpg_005fparam_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fpg_005findex_0026_005fexport.release();
    _005fjspx_005ftagPool_005fpg_005fpage.release();
    _005fjspx_005ftagPool_005fpg_005ffirst.release();
    _005fjspx_005ftagPool_005fpg_005fprev.release();
    _005fjspx_005ftagPool_005fpg_005fpages.release();
    _005fjspx_005ftagPool_005fpg_005fnext.release();
    _005fjspx_005ftagPool_005fpg_005flast_0026_005fexport.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");

response.setHeader("Cache-Control","no-store");
response.setHeader("Pragma","no-cache");
response.setDateHeader ("Expires", 0);

      out.write('\r');
      out.write('\n');

int index = 0 ;
if(request.getParameter("pager.offset")!=null)
        index=Integer.parseInt(request.getParameter("pager.offset"));
int offset1 = index ;
int offset2 = 0;
String pageTime = request.getParameter("pageTime") ;
java.util.Locale.setDefault(java.util.Locale.CHINA);
String jumpFlag = request.getParameter("jumpFlag");
String validate=request.getParameter("validate");
String flag= request.getAttribute("flag")==null?"":request.getAttribute("flag").toString();

      out.write('\r');
      out.write('\n');
      //  html:html
      org.apache.struts.taglib.html.HtmlTag _jspx_th_html_005fhtml_005f0 = (org.apache.struts.taglib.html.HtmlTag) _005fjspx_005ftagPool_005fhtml_005fhtml.get(org.apache.struts.taglib.html.HtmlTag.class);
      boolean _jspx_th_html_005fhtml_005f0_reused = false;
      try {
        _jspx_th_html_005fhtml_005f0.setPageContext(_jspx_page_context);
        _jspx_th_html_005fhtml_005f0.setParent(null);
        int _jspx_eval_html_005fhtml_005f0 = _jspx_th_html_005fhtml_005f0.doStartTag();
        if (_jspx_eval_html_005fhtml_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n<link rel=stylesheet type=\"text/css\" href=\"/jsoa/style/cssmain.css\">\r\n<title>自定义菜单列表</title>\r\n\r\n<!--  STYLE\tCHANGE START -->\r\n<link href=\"skin/");
            out.print(session.getAttribute("skin"));
            out.write("/style-");
            out.print(session.getAttribute("browserVersion"));
            out.write(".css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<script\tsrc=\"js/js.js\" language=\"javascript\"></script>\r\n<!--  STYLE\tCHANGE START -->\r\n\r\n<script language=\"JavaScript\" src=\"js/date0.js\"></script>\r\n</head>\r\n<script language=\"JavaScript\">\r\n<!--\r\nfunction MM_openBrWindow(theURL,winName,features) { //v2.0\r\n  JSMainWinOpen(theURL,winName,features);\r\n}\r\n//-->\r\n</script>\r\n<link rel=stylesheet type=\"text/css\" href=\"/jsoa/public/date_picker/DateObject1.css\">\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/DateObject.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/DatePicker.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/editlib.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/tree.js\"></SCRIPT>\r\n\r\n<body    class=\"MainFrameBox\">\r\n\r\n<table width=\"100%\" border=0 cellpadding=\"0\" cellspacing=\"0\">\r\n<tr>\r\n<td>\r\n");

String errMsg = (request.getAttribute("errs") != null) ? (String)request.getAttribute("errs") : "";
if (errMsg.length() > 0) {

            out.write("\r\n<script>\r\nalert('");
            out.print(errMsg);
            out.write("');\r\n</script>\r\n");
}
            out.write("\r\n\r\n\r\n<!-- MIDDLE\tBUTTONS\t-->\r\n<table width=\"100%\"\theight=\"25\"\tborder=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n\t<tr>\r\n\t\t<td colspan=\"5\" align=\"right\">\r\n\t\t\t<button  class=\"btnButton2Font\" onclick=\"add()\">新增</button>\r\n\t\t\t<button  class=\"btnButton2Font\" onclick=\"delBatch()\">删除</button>\t\t\t\r\n\t\t</td>\r\n\t</tr>\r\n</table>\r\n<!-- MIDDLE\tBUTTONS\t-->\r\n\r\n\r\n<!-- LIST TITLE PART -->\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"listTable outtopline\">\r\n\t<tr>\r\n\t\t\t  <td class=\"listTableHead\" width=\"5%\" nowrap>\r\n\t\t\t\t<input type=\"checkbox\" name=\"chkSelect\" style=\"cursor:'hand'\" onclick=\"selectAll(this)\">\r\n\t\t\t  </td>\r\n\t\t\t  <td class=\"listTableHead\" width=\"20%\">菜单名称</td>\r\n\t\t\t  <td class=\"listTableHead\">用户范围</td>\r\n\t\t\t  <td class=\"listTableHead\" width=\"8%\">显示顺序</td>\r\n\t\t\t  <td class=\"listTableHead\" width=\"8%\">是否启用</td>\r\n\t\t\t  <td class=\"listTableHeadLast\" width=\"8%\" nowrap>处理</td>\r\n\t\t\t</tr>\r\n\r\n\t");

	java.util.List mylist = (java.util.List)request.getAttribute("mylist");
	if (mylist != null && mylist.size() > 0) {
	  boolean isroot = true;
	  String upMenuName = "";
	  String menuScope;
	  String menuOrder;
	  String tmpStr = "";
      String space ;
      String spaceT = "";
      String used;
      String listClass;
	  for(int i = 0; i < mylist.size(); i++){
		  Object[] obj = (Object[])mylist.get(i);
		  //DO NOT IN USE
		  //if (obj[3] != null && "0".equals(obj[3].toString())) continue;
		  index ++;
		  offset2++;
		  listClass="listTableLine1";
		  if(index%2 != 0){listClass="listTableLine2";}
		  menuScope=obj[7]==null?"":obj[7].toString();
		  menuOrder=obj[8]==null?"":obj[8].toString();

		  if(menuScope.equals("0") || menuScope.equals("")){
		     menuScope="&nbsp;";
		  }	  
		  
		  if("0".equals(menuOrder) || "".equals(menuOrder)){
		     menuOrder="&nbsp;";
		  }
	
            out.write("\r\n\t  <tr>\r\n\t  <!-- RECORD NUMBER -->\r\n\t  <td class=\"");
            out.print(listClass);
            out.write("\">\r\n          ");

              if (obj[2].toString().indexOf("-") > 0 && !"9".equals(obj[6].toString())) {
          
            out.write("\r\n           <input type=\"checkbox\" style=\"cursor:'hand'\" name=\"batchDel\" value=\"");
            out.print(obj[0]);
            out.write('"');
            out.write('>');
//=index
            out.write("\r\n          ");
} else if (obj[2].toString().indexOf("-") <= 0 && "8".equals(obj[6].toString())) {
            out.write("\r\n           <input type=\"checkbox\" style=\"cursor:'hand'\" name=\"batchDel\" value=\"");
            out.print(obj[4]);
            out.write('"');
            out.write('>');
//=index
            out.write("\r\n          ");
} else {
            out.write("\r\n          <input type=\"checkbox\" style=\"cursor:'hand'\" name=\"batchDel\" value=\"");
            out.print(obj[4]);
            out.write("\" disabled=\"disabled\">");
//=index
            out.write("\r\n          ");
}
            out.write("\r\n\t  </td>\r\n\r\n\t  <td class=\"");
            out.print(listClass);
            out.write("\" valign=\"middle\" height=\"22\" valign=\"top\">\r\n              ");

                  tmpStr = "";
                  space = obj[2].toString();
                  spaceT = "";
                  used=obj[3].toString();
                  if("0".equals(used)){
                	  used="否";
                  }else{
                	  used="是";
                  }
				  if("9".equals(obj[6].toString())){
					  space=space.substring(space.indexOf("-")+1);
				  }
                  for(int j = 0; j < space.length(); j++) {
					  
                      if (space.charAt(j) == '-') spaceT += "&nbsp;&nbsp;&nbsp;&nbsp;";
                  }
                  tmpStr = spaceT + obj[1].toString();
              
            out.write("\r\n              ");
if ("9".equals(obj[6].toString())) {
            out.write("\r\n                <a href=\"javascript:void(0);\" onclick=\"editOrigin('");
            out.print(obj[0]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[2]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[4]);
            out.write("')\">");
out.print(tmpStr);
            out.write("</a>\r\n              ");
} else {
            out.write("\r\n              <a href=\"javascript:void(0);\" onclick=\"edit('");
            out.print(obj[0]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[2]);
            out.write("')\">");
out.print(tmpStr);
            out.write("</a>\r\n              ");
}
            out.write("\r\n\t </td>\t\r\n\t <td class=\"");
            out.print(listClass);
            out.write('"');
            out.write('>');
            out.print(menuScope);
            out.write("</td>\r\n\t <td class=\"");
            out.print(listClass);
            out.write('"');
            out.write('>');
            out.print(menuOrder);
            out.write("</td>\r\n\t <td class=\"");
            out.print(listClass);
            out.write('"');
            out.write('>');
            out.print(used);
            out.write("</td>\r\n\t <td class=\"");
            out.print(listClass);
            out.write(" listTableLineLastTD\" valign=\"middle\"  nowrap><img  style=\"cursor:pointer\" border=\"0\" src=\"images/modi.gif\" alt=\"修改\" onclick=\"edit('");
            out.print(obj[0]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[2]);
            out.write("')\">");
if("1".equals(obj[3].toString())){
            out.write("&nbsp;<img  style=\"cursor:pointer\" border=\"0\" src=\"imges/noused.gif\" alt=\"隐藏\" onclick=\"hideMenu('");
            out.print(obj[0]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[2]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[4]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[6]);
            out.write("')\">");
}else{
            out.write("&nbsp;<img  style=\"cursor:pointer\" border=\"0\" src=\"imges/used.gif\"  alt=\"显示\" onclick=\"showMenu('");
            out.print(obj[0]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[2]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[4]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[6]);
            out.write("')\">");
}if ("8".equals(obj[6].toString())) {
            out.write("&nbsp;<img  style=\"cursor:pointer\" border=\"0\" src=\"images/del.gif\"  alt=\"删除\" onclick=\"del('");
            out.print(obj[4]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[2]);
            out.write("')\" >");
} else {
            out.write("&nbsp;<img  style=\"cursor:pointer\" border=\"0\" src=\"images/del.gif\" alt=\"删除\" onclick=\"del('");
            out.print(obj[0]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(obj[2]);
            out.write("')\" >");
}
            out.write("\r\n            </td>\r\n\t</tr>\r\n\t");
}}
            out.write("\r\n</table>\r\n<!-- LIST TITLE PART -->\r\n\r\n\r\n\r\n\r\n<!-- PAGER -->\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"pagebar\">\r\n <tr>\r\n    <td>\r\n\t  ");
String pagerURL = "/jsoa/ModuleSetAction.do";
            out.write("\r\n\t  ");
            out.write("\r\n\r\n<div><table width=\"100%\" height=\"22\">\r\n  <tr>\r\n    <td height=\"22\" align=\"right\" width=\"100%\">\r\n");

String page_local = session.getAttribute("org.apache.struts.action.LOCALE").toString();
int recordCount=Integer.parseInt((String)request.getAttribute("recordCount"));
StringBuffer pager_query_string=new StringBuffer(pagerURL);

                int maxPageItems=Integer.parseInt((String)request.getAttribute("maxPageItems"));
				String pageParameters=(String)request.getAttribute("pageParameters");
                String[] paraArray=null;
                if(pageParameters!=null && !pageParameters.equals("null")){
                    paraArray=pageParameters.split(",");
                }
                
				if(recordCount>maxPageItems){
                
            out.write("\r\n                ");
            //  pg:pager
            com.jsptags.navigation.pager.PagerTag _jspx_th_pg_005fpager_005f0 = (com.jsptags.navigation.pager.PagerTag) _005fjspx_005ftagPool_005fpg_005fpager_0026_005furl_005fscope_005fmaxPageItems_005fmaxIndexPages_005fitems_005fisOffset_005findex_005fexport.get(com.jsptags.navigation.pager.PagerTag.class);
            boolean _jspx_th_pg_005fpager_005f0_reused = false;
            try {
              _jspx_th_pg_005fpager_005f0.setPageContext(_jspx_page_context);
              _jspx_th_pg_005fpager_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fhtml_005f0);
              // /public/page/pager.jsp(20,16) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_pg_005fpager_005f0.setUrl(pagerURL);
              // /public/page/pager.jsp(20,16) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_pg_005fpager_005f0.setItems(recordCount);
              // /public/page/pager.jsp(20,16) name = maxPageItems type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_pg_005fpager_005f0.setMaxPageItems(maxPageItems);
              // /public/page/pager.jsp(20,16) name = maxIndexPages type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_pg_005fpager_005f0.setMaxIndexPages(8);
              // /public/page/pager.jsp(20,16) name = isOffset type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_pg_005fpager_005f0.setIsOffset(false);
              // /public/page/pager.jsp(20,16) name = index type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_pg_005fpager_005f0.setIndex("center");
              // /public/page/pager.jsp(20,16) name = export type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_pg_005fpager_005f0.setExport("offset,currentPageNumber=pageNumber");
              // /public/page/pager.jsp(20,16) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_pg_005fpager_005f0.setScope("request");
              int _jspx_eval_pg_005fpager_005f0 = _jspx_th_pg_005fpager_005f0.doStartTag();
              if (_jspx_eval_pg_005fpager_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                java.lang.Integer offset = null;
                java.lang.Integer currentPageNumber = null;
                offset = (java.lang.Integer) _jspx_page_context.findAttribute("offset");
                currentPageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("currentPageNumber");
                do {
                  out.write("\r\n                    ");

					if(paraArray!=null){
                    for(int pageParaIndex=0;pageParaIndex<paraArray.length;pageParaIndex++){
                    	if(pageParaIndex==0){
                    		pager_query_string.append("?");
                    	}else{
                    		pager_query_string.append("&");
                    	}
                    	if(request.getParameter(paraArray[pageParaIndex])!=null){
                    		pager_query_string.append(paraArray[pageParaIndex]).append("=").append(request.getParameter(paraArray[pageParaIndex]));
                    	}
                    	if(pager_query_string.toString().endsWith("&")){
                    	   pager_query_string = pager_query_string.deleteCharAt(pager_query_string.length()-1);
                    	}
                    
                  out.write("\r\n                    ");
                  //  pg:param
                  com.jsptags.navigation.pager.ParamTag _jspx_th_pg_005fparam_005f0 = (com.jsptags.navigation.pager.ParamTag) _005fjspx_005ftagPool_005fpg_005fparam_0026_005fname_005fnobody.get(com.jsptags.navigation.pager.ParamTag.class);
                  boolean _jspx_th_pg_005fparam_005f0_reused = false;
                  try {
                    _jspx_th_pg_005fparam_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_pg_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005fpager_005f0);
                    // /public/page/pager.jsp(45,20) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_pg_005fparam_005f0.setName(paraArray[pageParaIndex]);
                    int _jspx_eval_pg_005fparam_005f0 = _jspx_th_pg_005fparam_005f0.doStartTag();
                    if (_jspx_th_pg_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fpg_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_pg_005fparam_005f0);
                    _jspx_th_pg_005fparam_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fparam_005f0_reused);
                  }
                  out.write("\r\n                    ");
}
					}
                  out.write("\r\n                    ");
                  //  pg:index
                  com.jsptags.navigation.pager.IndexTag _jspx_th_pg_005findex_005f0 = (com.jsptags.navigation.pager.IndexTag) _005fjspx_005ftagPool_005fpg_005findex_0026_005fexport.get(com.jsptags.navigation.pager.IndexTag.class);
                  boolean _jspx_th_pg_005findex_005f0_reused = false;
                  try {
                    _jspx_th_pg_005findex_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_pg_005findex_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005fpager_005f0);
                    // /public/page/pager.jsp(48,20) name = export type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_pg_005findex_005f0.setExport("pageCount,itemCount");
                    int _jspx_eval_pg_005findex_005f0 = _jspx_th_pg_005findex_005f0.doStartTag();
                    if (_jspx_eval_pg_005findex_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      java.lang.Integer itemCount = null;
                      java.lang.Integer pageCount = null;
                      itemCount = (java.lang.Integer) _jspx_page_context.findAttribute("itemCount");
                      pageCount = (java.lang.Integer) _jspx_page_context.findAttribute("pageCount");
                      do {
                        out.write("\r\n                    ");

                    if(request.getAttribute("pager.realCurrent")!=null){
                        currentPageNumber=new Integer(request.getAttribute("pager.realCurrent").toString());
                    }
                    if(maxPageItems!=recordCount){
                    
                        out.write("\r\n                    ");
                        //  pg:page
                        com.jsptags.navigation.pager.PageTag _jspx_th_pg_005fpage_005f0 = (com.jsptags.navigation.pager.PageTag) _005fjspx_005ftagPool_005fpg_005fpage.get(com.jsptags.navigation.pager.PageTag.class);
                        boolean _jspx_th_pg_005fpage_005f0_reused = false;
                        try {
                          _jspx_th_pg_005fpage_005f0.setPageContext(_jspx_page_context);
                          _jspx_th_pg_005fpage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                          int _jspx_eval_pg_005fpage_005f0 = _jspx_th_pg_005fpage_005f0.doStartTag();
                          if (_jspx_eval_pg_005fpage_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            java.lang.String pageUrl = null;
                            java.lang.Integer pageNumber = null;
                            pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                            pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                            do {
                              out.write("\r\n                        ");

                        if(request.getAttribute("pager.realCurrent")!=null){
                            pageNumber=new Integer(request.getAttribute("pager.realCurrent").toString());
                        }
                        
                              out.print(com.js.lang.Resource.getValue(page_local,"common","comm.pager3"));
                              out.print(itemCount);
                              out.print(com.js.lang.Resource.getValue(page_local,"common","comm.pager4"));
                              out.write("\r\n                       ");
                              out.print(com.js.lang.Resource.getValue(page_local,"common","comm.pager1"));
                              out.write("<font color=\"red\">");
                              out.print(pageNumber);
                              out.write("</font>/");
                              out.print(pageCount);
                              out.print(com.js.lang.Resource.getValue(page_local,"common","comm.pager2"));
                              out.write("\r\n                       \r\n                    ");
                              int evalDoAfterBody = _jspx_th_pg_005fpage_005f0.doAfterBody();
                              pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                              pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                          }
                          if (_jspx_th_pg_005fpage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fpg_005fpage.reuse(_jspx_th_pg_005fpage_005f0);
                          _jspx_th_pg_005fpage_005f0_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fpage_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fpage_005f0_reused);
                        }
                        out.write("\r\n                    &nbsp;\r\n                    \r\n                     ");
                        //  pg:first
                        com.jsptags.navigation.pager.FirstTag _jspx_th_pg_005ffirst_005f0 = (com.jsptags.navigation.pager.FirstTag) _005fjspx_005ftagPool_005fpg_005ffirst.get(com.jsptags.navigation.pager.FirstTag.class);
                        boolean _jspx_th_pg_005ffirst_005f0_reused = false;
                        try {
                          _jspx_th_pg_005ffirst_005f0.setPageContext(_jspx_page_context);
                          _jspx_th_pg_005ffirst_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                          int _jspx_eval_pg_005ffirst_005f0 = _jspx_th_pg_005ffirst_005f0.doStartTag();
                          if (_jspx_eval_pg_005ffirst_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            java.lang.String pageUrl = null;
                            java.lang.Integer pageNumber = null;
                            pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                            pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                            do {
                              out.write("\r\n                        ");
if(currentPageNumber.intValue()!=1){
                              out.write("\r\n                          <a href=\"");
                              out.print( pageUrl );
                              out.write("\"><img src=\"/jsoa/images/p_first.gif\" border=0 title=\"首页\"></a>\r\n                         ");
}else{
                              out.write("\r\n                         <img src=\"/jsoa/images/p_first2.gif\" border=0>\r\n                         ");
} 
                              out.write("\r\n                    ");
                              int evalDoAfterBody = _jspx_th_pg_005ffirst_005f0.doAfterBody();
                              pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                              pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                          }
                          if (_jspx_th_pg_005ffirst_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fpg_005ffirst.reuse(_jspx_th_pg_005ffirst_005f0);
                          _jspx_th_pg_005ffirst_005f0_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005ffirst_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005ffirst_005f0_reused);
                        }
                        out.write("\r\n                    ");
if(currentPageNumber.intValue()!=1){
                        out.write("\r\n                    ");
                        //  pg:prev
                        com.jsptags.navigation.pager.PrevTag _jspx_th_pg_005fprev_005f0 = (com.jsptags.navigation.pager.PrevTag) _005fjspx_005ftagPool_005fpg_005fprev.get(com.jsptags.navigation.pager.PrevTag.class);
                        boolean _jspx_th_pg_005fprev_005f0_reused = false;
                        try {
                          _jspx_th_pg_005fprev_005f0.setPageContext(_jspx_page_context);
                          _jspx_th_pg_005fprev_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                          int _jspx_eval_pg_005fprev_005f0 = _jspx_th_pg_005fprev_005f0.doStartTag();
                          if (_jspx_eval_pg_005fprev_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            java.lang.String pageUrl = null;
                            java.lang.Integer pageNumber = null;
                            pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                            pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                            do {
                              out.write("\r\n                         <a href=\"");
                              out.print( pageUrl );
                              out.write("\"><img src=\"/jsoa/images/p_pre.gif\" border=0 title=\"上一页\"></a>\r\n                    ");
                              int evalDoAfterBody = _jspx_th_pg_005fprev_005f0.doAfterBody();
                              pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                              pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                          }
                          if (_jspx_th_pg_005fprev_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fpg_005fprev.reuse(_jspx_th_pg_005fprev_005f0);
                          _jspx_th_pg_005fprev_005f0_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fprev_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fprev_005f0_reused);
                        }
                        out.write("\r\n                    ");
}else{ 
                        out.write("\r\n                    <img src=\"/jsoa/images/p_pre2.gif\" border=0 >\r\n                    ");
} 
                        out.write("\r\n                    \r\n                   \r\n                    ");
                        //  pg:pages
                        com.jsptags.navigation.pager.PagesTag _jspx_th_pg_005fpages_005f0 = (com.jsptags.navigation.pager.PagesTag) _005fjspx_005ftagPool_005fpg_005fpages.get(com.jsptags.navigation.pager.PagesTag.class);
                        boolean _jspx_th_pg_005fpages_005f0_reused = false;
                        try {
                          _jspx_th_pg_005fpages_005f0.setPageContext(_jspx_page_context);
                          _jspx_th_pg_005fpages_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                          int _jspx_eval_pg_005fpages_005f0 = _jspx_th_pg_005fpages_005f0.doStartTag();
                          if (_jspx_eval_pg_005fpages_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            java.lang.String pageUrl = null;
                            java.lang.Integer pageNumber = null;
                            if (_jspx_eval_pg_005fpages_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_pg_005fpages_005f0);
                            }
                            pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                            pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                            do {
                              out.write("\r\n                        ");

                        if (pageNumber.intValue() == currentPageNumber.intValue()) {
                              out.write("\r\n                        <span class=\"curPage\">");
                              out.print( pageNumber );
                              out.write("</span>\r\n                        ");
}else{
                              out.write("\r\n                        <a href=\"");
                              out.print( pageUrl );
                              out.write('"');
                              out.write('>');
                              out.print( pageNumber );
                              out.write("</a>\r\n                        ");
}
                              out.write("\r\n                    ");
                              int evalDoAfterBody = _jspx_th_pg_005fpages_005f0.doAfterBody();
                              pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                              pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_pg_005fpages_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                            }
                          }
                          if (_jspx_th_pg_005fpages_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fpg_005fpages.reuse(_jspx_th_pg_005fpages_005f0);
                          _jspx_th_pg_005fpages_005f0_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fpages_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fpages_005f0_reused);
                        }
                        out.write("\r\n                    ");
if(!currentPageNumber.equals(pageCount)){
                        out.write("\r\n                    ");
                        //  pg:next
                        com.jsptags.navigation.pager.NextTag _jspx_th_pg_005fnext_005f0 = (com.jsptags.navigation.pager.NextTag) _005fjspx_005ftagPool_005fpg_005fnext.get(com.jsptags.navigation.pager.NextTag.class);
                        boolean _jspx_th_pg_005fnext_005f0_reused = false;
                        try {
                          _jspx_th_pg_005fnext_005f0.setPageContext(_jspx_page_context);
                          _jspx_th_pg_005fnext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                          int _jspx_eval_pg_005fnext_005f0 = _jspx_th_pg_005fnext_005f0.doStartTag();
                          if (_jspx_eval_pg_005fnext_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            java.lang.String pageUrl = null;
                            java.lang.Integer pageNumber = null;
                            pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                            pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                            do {
                              out.write("\r\n                         <a href=\"");
                              out.print( pageUrl );
                              out.write("\"><img src=\"/jsoa/images/p_next.gif\" border=0 title=\"下一页\"></a>\r\n                    ");
                              int evalDoAfterBody = _jspx_th_pg_005fnext_005f0.doAfterBody();
                              pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                              pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                          }
                          if (_jspx_th_pg_005fnext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fpg_005fnext.reuse(_jspx_th_pg_005fnext_005f0);
                          _jspx_th_pg_005fnext_005f0_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fnext_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fnext_005f0_reused);
                        }
                        out.write("\r\n                    ");
}else{ 
                        out.write("\r\n                    <img src=\"/jsoa/images/p_next2.gif\" border=0>\r\n                    ");
} 
                        out.write("\r\n                    \r\n                    ");
                        //  pg:last
                        com.jsptags.navigation.pager.LastTag _jspx_th_pg_005flast_005f0 = (com.jsptags.navigation.pager.LastTag) _005fjspx_005ftagPool_005fpg_005flast_0026_005fexport.get(com.jsptags.navigation.pager.LastTag.class);
                        boolean _jspx_th_pg_005flast_005f0_reused = false;
                        try {
                          _jspx_th_pg_005flast_005f0.setPageContext(_jspx_page_context);
                          _jspx_th_pg_005flast_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                          // /public/page/pager.jsp(98,20) name = export type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_pg_005flast_005f0.setExport("pageUrl");
                          int _jspx_eval_pg_005flast_005f0 = _jspx_th_pg_005flast_005f0.doStartTag();
                          if (_jspx_eval_pg_005flast_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            java.lang.String pageUrl = null;
                            pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                            do {
                              out.write("\r\n                        ");
if(!currentPageNumber.equals(pageCount)){
                              out.write("\r\n                         <a href=\"");
                              out.print( pageUrl );
                              out.write("\"><img src=\"/jsoa/images/p_last.gif\" border=0 title=\"尾页\"></a>\r\n                         ");
}else{
                              out.write("\r\n                         <img src=\"/jsoa/images/p_last2.gif\" border=0>\r\n                         ");
} 
                              out.write("\r\n                    ");
                              int evalDoAfterBody = _jspx_th_pg_005flast_005f0.doAfterBody();
                              pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                          }
                          if (_jspx_th_pg_005flast_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fpg_005flast_0026_005fexport.reuse(_jspx_th_pg_005flast_005f0);
                          _jspx_th_pg_005flast_005f0_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005flast_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005flast_005f0_reused);
                        }
                        out.write("\r\n                    \r\n                    \r\n                    ");
}
                        out.write("\r\n                    ");
                        int evalDoAfterBody = _jspx_th_pg_005findex_005f0.doAfterBody();
                        itemCount = (java.lang.Integer) _jspx_page_context.findAttribute("itemCount");
                        pageCount = (java.lang.Integer) _jspx_page_context.findAttribute("pageCount");
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                    }
                    if (_jspx_th_pg_005findex_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fpg_005findex_0026_005fexport.reuse(_jspx_th_pg_005findex_005f0);
                    _jspx_th_pg_005findex_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005findex_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005findex_005f0_reused);
                  }
                  out.write("\r\n                    ");
                  int evalDoAfterBody = _jspx_th_pg_005fpager_005f0.doAfterBody();
                  offset = (java.lang.Integer) _jspx_page_context.findAttribute("offset");
                  currentPageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("currentPageNumber");
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_pg_005fpager_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fpg_005fpager_0026_005furl_005fscope_005fmaxPageItems_005fmaxIndexPages_005fitems_005fisOffset_005findex_005fexport.reuse(_jspx_th_pg_005fpager_005f0);
              _jspx_th_pg_005fpager_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fpager_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fpager_005f0_reused);
            }
            out.write("\t\t\t\t\t\r\n\t\t\t\t\t&nbsp;第&nbsp;<input id=\"inputPageNum\" type=\"text\" style=\"height:18px;\" name=\"page_jump_num\" size=3 onKeyUp=\"this.value=this.value.replace(/\\D/g,'')\" onafterpaste=\"this.value=this.value.replace(/\\D/g,'')\">&nbsp;页&nbsp;<input type=\"button\" class=\"btnButton4Font\" style=\"height:18px;margin-bottom:7px;\" value=\"Go\" onclick=\"page_go_jump()\"></input>\r\n\t\t\t\t\t");
}
            out.write("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</table>\r\n</div>\r\n\r\n<script language =\"javascript\">\r\nfunction page_go_jump(){\r\n   var pageNum=document.getElementById(\"inputPageNum\").value;\r\n   if(!parseInt(pageNum,10)>0)\r\n   {\r\n   \t\talert(\"请输入正确的页码!\");\r\n   \t\tdocument.getElementById(\"inputPageNum\").value=\"\";\r\n   \t\treturn;\r\n   }\r\n   var num=document.all.page_jump_num.value;\r\n   if(checkNUM(num)==0)num=0;\r\n   var recordCount=");
            out.print(recordCount);
            out.write(";\r\n   var maxPageItems=");
            out.print(maxPageItems);
            out.write(";\r\n   \r\n   var maxPageNum=parseInt((recordCount/maxPageItems))+1;\r\n   \r\n   if(num>maxPageNum){\r\n      num=(maxPageNum-1)*15;\r\n   }else{\r\n      num=(num-1)*15;\r\n   }\r\n   location.href=\"");
            out.print(pager_query_string.toString());
            out.write("&pager.offset=\"+num;\r\n}\r\n\r\nfunction checkNUM(NUM)\r\n{\r\n\tvar i,j,strTemp;\r\n\tstrTemp=\"0123456789\";\r\n\tif ( NUM.length== 0)\r\n\t\treturn 0\r\n\tfor (i=0;i<NUM.length;i++)\r\n\t{\r\n\t\tj=strTemp.indexOf(NUM.charAt(i));\r\n\t\tif (j==-1)\r\n\t\t{\r\n\t\t\t//说明有字符不是数字\r\n\t\t\treturn 0;\r\n\t\t}\r\n\t}\r\n\t//说明是数字\r\n\treturn 1;\r\n}\r\n</script>\r\n");
            out.write("\r\n\t  </td>\r\n\t</tr>\r\n</table>\r\n<!-- PAGER -->\r\n\r\n</td>\r\n</tr>\r\n</table>\r\n\r\n</body>\r\n\r\n<script language=\"javascript\">\r\nvar flag=\"");
            out.print(flag);
            out.write("\";\r\nif(\"foraudit\"==flag){\r\n\talert(\"数据已提交审计管理员审核！\");\r\n}\r\n//添加\r\nfunction add() {\r\n    var hhref  = \"/jsoa/ModuleSetAction.do?action=toAdd\";\r\n    MM_openBrWindow(hhref,\"\",\"TOP=0,LEFT=0,scrollbars=yes,resizable=yes,width=800,height=600\") ;\r\n}\r\n//编辑\r\nfunction edit(editId, level) {\r\n    var hhref = \"/jsoa/ModuleSetAction.do?action=load&pager.offset=");
            out.print(offset1);
            out.write("&validate=");
            out.print(validate);
            out.write("\" ;\r\n    hhref +=  \"&menuId=\" + editId + \"&loadstyle=1&level=\" + level;\r\n    MM_openBrWindow(hhref,\"\",\"TOP=0,LEFT=0,scrollbars=yes,resizable=yes,width=800,height=600\")\r\n}\r\nfunction editOrigin(menuId,menuLevel,menuSetId) {\r\n    MM_openBrWindow('/jsoa/MenuAction.do?action=load&modifyId='+menuSetId+'&custMenuId='+menuId+'&menuLevel='+menuLevel+'&pager.offset=");
            out.print(offset1);
            out.write("&validate=");
            out.print(validate);
            out.write("','','TOP=0,LEFT=0,scrollbars=yes,resizable=yes,width=700,height=500');\r\n}\r\nfunction doAction(editId) {\r\n  var hhref = \"/jsoa/ModuleDealwithAction.do?action=getPage&validate=");
            out.print(validate);
            out.write("\" ;\r\n    hhref +=  \"&menuId=\"+editId ;\r\n    window.location.href = ((window.location.href).substring(0,(window.location.href).indexOf(\"/jsoa\")))+hhref;\r\n}\r\n//删除全部\r\nfunction delAll() {\r\n     if(confirm(\"将删除所有菜单定义， 您确定吗？\")){\r\n         window.location.href=((window.location.href).substring(0,(window.location.href).indexOf(\"/jsoa\")))+\"/jsoa/ModuleSetAction.do?action=delAll&validate=");
            out.print(validate);
            out.write("\";\r\n    }\r\n}\r\n\r\nfunction showMenu(menuId,menuLevel,menuLocation,menuCount){\r\n\tif(confirm(\"将显示您所选择的菜单及下属子菜单，您确定吗？\")){\r\n\t\twindow.location.href=((window.location.href).substring(0,(window.location.href).indexOf(\"/jsoa\")))+\"/jsoa/ModuleSetAction.do?action=showMenu&menuId=\"+menuId+\"&menuLevel=\"+menuLevel+\"&menuLocation=\"+menuLocation+\"&menuCount=\"+menuCount+\"&validate=");
            out.print(validate);
            out.write("&pager.offset=");
            out.print(offset1);
            out.write("\";\r\n\t}\r\n}\r\n\r\nfunction hideMenu(menuId,menuLevel,menuLocation,menuCount){\r\n\tif(confirm(\"将隐藏您所选择的菜单及下属子菜单，您确定吗？\")){\r\n\t\twindow.location.href=((window.location.href).substring(0,(window.location.href).indexOf(\"/jsoa\")))+\"/jsoa/ModuleSetAction.do?action=hideMenu&menuId=\"+menuId+\"&menuLevel=\"+menuLevel+\"&menuLocation=\"+menuLocation+\"&menuCount=\"+menuCount+\"&validate=");
            out.print(validate);
            out.write("&pager.offset=");
            out.print(offset1);
            out.write("\";\r\n\t}\r\n}\r\n\r\n//批量删除\r\nfunction delBatch() {\r\n    var ids = getCheckBoxID();\r\n    //alert(ids);\r\n    if(ids == \"\") {\r\n        alert(\"没有选择记录！\") ;\r\n    } else {\r\n         if(confirm(\"如果包含子菜单也将被删除！\")) {\r\n             window.location.href=((window.location.href).substring(0,(window.location.href).indexOf(\"/jsoa\")))+\"/jsoa/ModuleSetAction.do?action=delBatch&ids=\" +ids+\"&pager.offset=0&validate=");
            out.print(validate);
            out.write("\";\r\n        }\r\n    }\r\n }\r\n\r\n//单个删除\r\nfunction del(id, level) {\r\n");
 int deloff = offset2==1 ?  offset1 -15:offset1;
   if(deloff < 0) deloff = 0 ;
 
            out.write("\r\n     if(confirm(\"如果包含子菜单也将被删除！\")){\r\n         window.location.href=((window.location.href).substring(0,(window.location.href).indexOf(\"/jsoa\")))+\"/jsoa/ModuleSetAction.do?level=\" + level + \"&action=delBatch&ids=\"+id+\"&pager.offset=");
            out.print(deloff);
            out.write("&validate=");
            out.print(validate);
            out.write("\";\r\n    }\r\n}\r\n\r\n//全选|全除\r\nfunction selectAll(obj) {\r\n    var checks;\r\n    checks = document.getElementsByName(\"batchDel\");\r\n    if (checks) {\r\n        //alert(checks.length);\r\n        for(var i = 0 ; i < checks.length ; i++ ) {\r\n            var chkObj = checks[i] ;\r\n            if (chkObj.disabled=='')\r\n                chkObj.checked = !chkObj.checked;\r\n        }\r\n    }\r\n}\r\n\r\nfunction getCheckBoxID() {\r\n    var retString=\"\" ;\r\n    var checks;\r\n    checks = document.getElementsByName(\"batchDel\");\r\n    if (checks) {\r\n        //alert(checks.length);\r\n        for(var i = 0 ; i < checks.length ; i++ ) {\r\n            var chkObj = checks[i] ;\r\n            if(chkObj.checked)\r\n            \tretString += chkObj.value + \",\";\r\n        }\r\n    }\r\n    return retString ;\r\n}\r\n</script>\r\n");
            int evalDoAfterBody = _jspx_th_html_005fhtml_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_html_005fhtml_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fhtml_005fhtml.reuse(_jspx_th_html_005fhtml_005f0);
        _jspx_th_html_005fhtml_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fhtml_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fhtml_005f0_reused);
      }
      out.write("\r\n<script src=\"/jsoa/js/util.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
