/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2023-01-06 09:53:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.zky;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class zkyScore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
String tableName = request.getParameter("t");
String fs = request.getParameter("f");

      out.write("\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n<html>\r\n\t<head></head>\r\n\t<body>\r\n\t<script type=\"text/javascript\">\r\n\tfunction getScore(){\r\n\t\tif(parent.window.document.getElementById(\"");
      out.print(fs );
      out.write("\")!=null){\r\n\t\t\tparent.window.document.getElementById(\"");
      out.print(fs );
      out.write("\").value=getFs(\"");
      out.print(tableName );
      out.write("\");\r\n\t\t}\r\n\t}\r\n\tfunction getFs(tableName){\r\n\t\tvar number = 0;\r\n\t\tif(tableName==\"t_grxx\"){//个人信息\r\n\t\t\tvar mark = parent.window.document.getElementById(\"grxx_sxyrzqk\").value;//任职情况\r\n\t\t\tif(mark==\"1\" || mark==\"2\" || mark == \"3\"){//院领导、所长、副所长\r\n\t\t\t\tnumber = 15;\r\n\t\t\t}else if(mark==\"4\"){//实验室主任\r\n\t\t\t\tnumber = 8;\r\n\t\t\t}\r\n\t\t}else if(tableName==\"t_lwzz\"){//论文专著\r\n\t\t\tvar lwzz_zl = parent.window.document.getElementById(\"lwzz_zl\").value;//种类\r\n\t\t\tvar lwzz_zzlx = parent.window.document.getElementById(\"lwzz_zzlx\").value;//著作类型\r\n\t\t\tvar lwzz_lwlx = parent.window.document.getElementById(\"lwzz_lwlx\").value;//论文类型\r\n\t\t\tvar lwzz_zzrs = parent.window.document.getElementById(\"lwzz_zzrs\").value;//作者人数\r\n\t\t\tif(lwzz_zzrs==\"\"){\r\n\t\t\t\tlwzz_zzrs = \"1\";\r\n\t\t\t\tparent.window.document.getElementById(\"lwzz_zzrs\").value=\"1\";\r\n\t\t\t}\r\n\t\t\tif(\"1\"==lwzz_zl){//论文\r\n\t\t\t\tif(\"1\"==lwzz_lwlx||\"2\"==lwzz_lwlx){//SUM,EI每篇SCI=25分/作者人数\r\n\t\t\t\t\tnumber = 25;\r\n\t\t\t\t}else if(\"3\"==lwzz_lwlx){//B=SUM每篇EI，核心=15分/作者人数\r\n\t\t\t\t\tnumber = 15;\r\n\t\t\t\t}else {//C=SUM每篇会议论文，其他论文=8分/作者人数\r\n\t\t\t\t\tnumber = 8;\r\n");
      out.write("\t\t\t\t}\r\n\t\t\t}else if(\"2\"==lwzz_zl){//著作\r\n\t\t\t\tif (\"1\"==lwzz_zzlx) {//D=SUM每本英文专著=100分/作者人数\r\n\t\t\t\t\tnumber = 100;\r\n\t\t\t\t} else if (\"2\"==lwzz_zzlx) {//E=SUM每本中文专著=60分/作者人数\r\n\t\t\t\t\tnumber = 60;\r\n\t\t\t\t} else if (\"3\"==lwzz_zzlx||\"4\"==lwzz_zzlx) {//F=SUM每本译著、其他=30分/作者人数\r\n\t\t\t\t\tnumber = 30;\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\tnumber = number/parseInt(lwzz_zzrs)\r\n\t\t}else if(tableName==\"t_yhdjx\"){//已获奖励\r\n\t\t\tvar yhdjx_jllb = parent.window.document.getElementById(\"yhdjx_jllb\").value;//奖励类别\r\n\t\t\tvar yhdjx_jldj = parent.window.document.getElementById(\"yhdjx_jldj\").value;//奖励等级\r\n\t\t\tvar yhdjx_wcrs = parent.window.document.getElementById(\"yhdjx_wcrs\").value;//完成人数\r\n\t\t\tif(yhdjx_wcrs==\"\"){\r\n\t\t\t\tyhdjx_wcrs = \"1\";\r\n\t\t\t\tparent.window.document.getElementById(\"yhdjx_wcrs\").value=\"1\";\r\n\t\t\t}\r\n\t\t\tvar mark = yhdjx_jllb+\"_\"+yhdjx_jldj;\r\n\t\t\tif(\"1_1\"==mark){//国家三大奖 特等奖\r\n\t\t\t\tnumber = 500;\r\n\t\t\t}else if(\"1_2\"==mark){//国家三大奖 一等奖\r\n\t\t\t\tnumber = 300;\r\n\t\t\t}else if(\"1_3\"==mark){//国家三大奖 二等奖\r\n\t\t\t\tnumber = 200;\r\n\t\t\t}else if(\"2_2\"==mark){//省部级奖 一等奖\r\n\t\t\t\tnumber = 100;\r\n\t\t\t}else if(\"2_3\"==mark){//省部级奖 二等奖\r\n");
      out.write("\t\t\t\tnumber = 50;\r\n\t\t\t}else if(\"2_4\"==mark){//省部级奖 三等奖\r\n\t\t\t\tnumber = 25;\r\n\t\t\t}else{\r\n\t\t\t\tnumber = 500;//其他取最高分\r\n\t\t\t}\r\n\t\t\tnumber = number/parseInt(yhdjx_wcrs);\r\n\t\t}else if(tableName==\"t_zzsbjx\"){//正在申报奖励\r\n\t\t\tvar zzsbjx_lx = parent.window.document.getElementById(\"zzsbjx_lx\").value;//申报类型\r\n\t\t\tif(\"1\"==zzsbjx_lx){//国家三大奖\r\n\t\t\t\tnumber = 20;\r\n\t\t\t}else if(\"2\"==zzsbjx_lx){//地方奖项\r\n\t\t\t\tnumber = 8;\r\n\t\t\t}else if(\"\"!=zzsbjx_lx){//其他\r\n\t\t\t\tnumber = 5;\r\n\t\t\t}\r\n\t\t}else if(tableName==\"t_sbzl\"){//申报专利\r\n\t\t\tnumber = 5;\r\n\t\t}else if(tableName==\"t_xshy\"){//学术会议\r\n\t\t\tvar xshy_hylx = parent.window.document.getElementById(\"xshy_hylx\").value;//会议类型\r\n\t\t\tvar xshy_bglx = parent.window.document.getElementById(\"xshy_bglx\").value;//报告类型\r\n\t\t\tvar xshy_zzrs = parent.window.document.getElementById(\"xshy_zzrs\").value;//人数\r\n\t\t\tif(\"\"==xshy_zzrs) parent.window.document.getElementById(\"xshy_zzrs\").value=\"1\";\r\n\t\t\tvar mark = xshy_hylx+\"_\"+xshy_bglx;\r\n\t\t\tif(\"1_1\"==mark){//国际会议邀请报告 5分/篇；\r\n\t\t\t\tnumber = 5;\r\n\t\t\t}else if(\"2_1\"==mark){//国内会议邀请报告 3分/篇\r\n\t\t\t\tnumber = 3;\r\n");
      out.write("\t\t\t}\r\n\t\t}else if(tableName==\"t_kyxm\"){//科研项目\r\n\t\t\tvar kyxm_xmlx = parent.window.document.getElementById(\"kyxm_xmlx\").value;//项目类型\r\n\t\t\tvar kyxm_cjfs = parent.window.document.getElementById(\"kyxm_cjfs\").value;//参加方式\r\n\t\t\tvar mark = kyxm_xmlx+\"_\"+kyxm_cjfs;\r\n\t\t\t/*\r\n\t\t\t A=国家重大项目973、863；基金委重点、重大基金；主持  20分/项\r\n\t         B=国家重大项目973、863；基金委重点、重大基金；参加  8分/项\r\n\t         C=基金委面上、青年基金项目负；主持   8分/项 参加 0\r\n\t         D=其他项目；主持；   8分/项  参加 0 \r\n\t\t\t */\r\n\t\t\tif(\"1_1\"==mark||\"2_1\"==mark){\r\n\t\t\t\tnumber = 20;\r\n\t\t\t}else if(\"1_2\"==mark||\"2_2\"==mark||\"3_1\"==mark||\"4_1\"==mark){\r\n\t\t\t\tnumber = 8;\r\n\t\t\t}\r\n\t\t}else if(tableName==\"t_rcpy\"){//人才培养\r\n\t\t\tvar rcpy_zdssrs = parent.window.document.getElementById(\"rcpy_zdssrs\").value;//在读硕士人数\r\n\t\t\tif(rcpy_zdssrs==\"\"){\r\n\t\t\t\trcpy_zdssrs = \"0\";\r\n\t\t\t\tparent.window.document.getElementById(\"rcpy_zdssrs\").value=\"0\";\r\n\t\t\t}\r\n\t\t\tvar rcpy_zdbsrs = parent.window.document.getElementById(\"rcpy_zdbsrs\").value;//在读博士人数\r\n\t\t\tif(rcpy_zdbsrs==\"\"){\r\n\t\t\t\trcpy_zdbsrs = \"0\";\r\n\t\t\t\tparent.window.document.getElementById(\"rcpy_zdbsrs\").value=\"0\";\r\n");
      out.write("\t\t\t}\r\n\t\t\tvar rcpy_skxs = parent.window.document.getElementById(\"rcpy_skxs\").value;//授课学时\r\n\t\t\tif(rcpy_skxs==\"\"){\r\n\t\t\t\trcpy_skxs = \"0\";\r\n\t\t\t\tparent.window.document.getElementById(\"rcpy_skxs\").value=\"0\";\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\tvar zdssrs = parseInt(rcpy_zdssrs)>4?4:parseInt(rcpy_zdssrs);//硕士人数\r\n\t\t\tvar zdbsrs = parseInt(rcpy_zdbsrs)>3?3:parseInt(rcpy_zdbsrs);//博士人数\r\n\t\t\tvar skxs = parseInt(rcpy_skxs);//授课学时\r\n\t\t\tnumber = number + (skxs*0.3);//讲授研究生课程  0.3/课时\r\n\t\t\tnumber = number + zdssrs*8;//在学硕士生      8/名\r\n\t\t\tnumber = number + zdbsrs*15;//在学博士生      15/名\r\n\t\t}else if(tableName==\"t_gjzzrz\"){//国际学术组织任职\r\n\t\t\tvar gjzzrz_drzw = parent.window.document.getElementById(\"gjzzrz_drzw\").value;//担任职务\r\n\t\t\tif(\"6\"==gjzzrz_drzw){//委员\r\n\t\t\t\tnumber = 2;\r\n\t\t\t}else if(\"\"!=gjzzrz_drzw){//主席、理事长、副主席、副理事长、秘书长\r\n\t\t\t\tnumber = 5;\r\n\t\t\t}\r\n\t\t}else if(tableName==\"t_gjqkrz\"){//国际期刊任职\r\n\t\t\tvar gjqkrz_drzw = parent.window.document.getElementById(\"gjqkrz_drzw\").value;//担任职务\r\n\t\t\tif(\"3\"==gjqkrz_drzw){//编委\r\n\t\t\t\tnumber = 2;\r\n\t\t\t}else if(\"\"!=gjqkrz_drzw){//主编、副主编\r\n\t\t\t\tnumber = 5;\r\n");
      out.write("\t\t\t}\r\n\t\t}else if(tableName==\"t_gjhyrz\"){//国际会议任职\r\n\t\t\tvar gjhyrz_drzw = parent.window.document.getElementById(\"gjhyrz_drzw\").value;//担任职务\r\n\t\t\tif(\"6\"==gjhyrz_drzw){//委员\r\n\t\t\t\tnumber = 2;\r\n\t\t\t}else if(\"\"!=gjhyrz_drzw){//主席、理事长、副主席、副理事长、秘书长\r\n\t\t\t\tnumber = 5;\r\n\t\t\t}\r\n\t\t}else if(tableName==\"t_cf\"){//出访\r\n\t\t\tnumber = 3;\r\n\t\t}else if(tableName==\"t_lf\"){//来访\r\n\t\t\tvar lf_lx = parent.window.document.getElementById(\"lf_lx\").value;//类型\r\n\t\t\tif(\"1\"==lf_lx){//专访\r\n\t\t\t\tnumber = 3;\r\n\t\t\t}else if(\"\"!=lf_lx){//顺访\r\n\t\t\t\tnumber = 1;\r\n\t\t\t}\r\n\t\t}else if(tableName==\"t_gjhz\"){//国际合作\r\n\t\t\tvar gjhz_lb = parent.window.document.getElementById(\"gjhz_lb\").value;//类型\r\n\t\t\tif(\"\"!=gjhz_lb){\r\n\t\t\t\tnumber = 15;\r\n\t\t\t}\r\n\t\t}else if(tableName==\"t_ydhz\"){//院际合作\r\n\t\t\tvar ydhz_xmjf = parent.window.document.getElementById(\"ydhz_xmjf\").value;//项目经费\r\n\t\t\tif(ydhz_xmjf==\"\"){\r\n\t\t\t\tydhz_xmjf = \"0\";\r\n\t\t\t\tparent.window.document.getElementById(\"ydhz_xmjf\").value=\"0\";\r\n\t\t\t}\r\n\t\t\tvar xmjf = parseFloat(ydhz_xmjf);\r\n\t\t\tif(xmjf>0&&xmjf<10){//经费低于10万\r\n\t\t\t\tnumber = 5;\r\n\t\t\t}else if(xmjf>=20){//经费高于20万\r\n");
      out.write("\t\t\t\tnumber = 15;\r\n\t\t\t}else if(xmjf>0){//经费在10到20万\r\n\t\t\t\tnumber = 10;\r\n\t\t\t}\r\n\t\t}else if(tableName==\"t_zxbg\"){//咨询报告\r\n\t\t\tvar zxbg_jb = parent.window.document.getElementById(\"zxbg_jb\").value;//级别\r\n\t\t\tif(\"1\"==zxbg_jb){//党和国家领导人\r\n\t\t\t\tnumber = 15;\r\n\t\t\t}else if(\"6\"==zxbg_jb){//其他\r\n\t\t\t\tnumber = 5;\r\n\t\t\t}else if(\"\"!=zxbg_jb){//综合部委、其他省部级、中办、国办\r\n\t\t\t\tnumber = 10;\r\n\t\t\t}\r\n\t\t}\r\n\t\treturn number.toFixed(2);\r\n\t}\r\n\t</script>\r\n\t</body>\r\n</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
