/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2023-01-06 10:09:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cooperate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.js.cooperate.po.*;
import com.js.lang.Resource;
import com.js.util.config.SystemCommon;

public final class body_005fdealwithmodify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-logic.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/public/jsp/modifyupload.jsp", Long.valueOf(1502704592000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-html.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-bean.tld", Long.valueOf(1499751390000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.js.cooperate.po");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.js.lang.Resource");
    _jspx_imports_classes.add("com.js.util.config.SystemCommon");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fhtml;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fhtml_005fhtml = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fhtml_005fhtml.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n\r\n\r\n");

response.setHeader("Cache-Control","no-store");
response.setHeader("Pragma","no-cache");
response.setDateHeader ("Expires", 0);

String userId=session.getAttribute("userId").toString();
String userName=session.getAttribute("userName").toString();
int i;
BodyPO bpo=(BodyPO)request.getAttribute("bodyInfo");
List attach=(List)request.getAttribute("bodyAttach");

String title=bpo.getTitle();
String content=bpo.getContent();

String fileServer = session.getAttribute("fileServer").toString();
Object[] obj;

int attchLen = 0;
if(attach != null){
	attchLen = attach.size();
}

String[] realFileArray=new String[attchLen];
String[] saveFileArray=new String[attchLen];

if(attach != null){
    for(i = 0; i < attchLen; i ++){
        obj = (Object[]) attach.get(i);
        realFileArray[i]=(String)obj[1];
        saveFileArray[i]=(String)obj[2];
    }
}


java.util.Map sysMap = com.js.system.util.SysSetupReader.getInstance().getSysSetupMap(session.getAttribute("domainId").toString());



      out.write('\r');
      out.write('\n');
      //  html:html
      org.apache.struts.taglib.html.HtmlTag _jspx_th_html_005fhtml_005f0 = (org.apache.struts.taglib.html.HtmlTag) _005fjspx_005ftagPool_005fhtml_005fhtml.get(org.apache.struts.taglib.html.HtmlTag.class);
      boolean _jspx_th_html_005fhtml_005f0_reused = false;
      try {
        _jspx_th_html_005fhtml_005f0.setPageContext(_jspx_page_context);
        _jspx_th_html_005fhtml_005f0.setParent(null);
        int _jspx_eval_html_005fhtml_005f0 = _jspx_th_html_005fhtml_005f0.doStartTag();
        if (_jspx_eval_html_005fhtml_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n<head>\r\n<title>修改协同工作</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=GBK\">\r\n<link href=\"/jsoa/skin/");
            out.print(session.getAttribute("skin"));
            out.write("/style-");
            out.print(session.getAttribute("browserVersion"));
            out.write(".css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<script src=\"/jsoa/js/js.js\" language=\"javascript\"></script>\r\n<link rel=stylesheet type=\"text/css\" href=\"/jsoa/public/date_picker/DateObject2.css\">\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/DateObject.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/DatePicker.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/editlib.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/tree.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/tree.js\"></SCRIPT>\r\n<SCRIPT language=\"javascript\" src=\"/jsoa/js/checkForm.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/js/openEndow.js\"></SCRIPT>\r\n\r\n<script src=\"/jsoa/js/toolbar/standardAdd.js\" language=\"javascript\"></script>\r\n<script src=\"/jsoa/js/clsPullXMenu.js\" language=\"javascript\"></script>\r\n<script src=\"/jsoa/js/cooperate/cooperatebtn.jsp?button=Send,Save,DrawFlow,Close\"></script>\r\n</head>\r\n\r\n<body leftmargin=\"0\" topmargin=\"0\" onload=\"loadHtmlEdit();\"  class=\"MainFrameBox Pupwin\">\r\n");
            out.write("<form name=\"frm\" action=\"/jsoa/BodyAction.do?flag=modifyContent\" method=\"post\">\r\n<input type=\"hidden\" name=\"bodyId\" value=\"");
            out.print(bpo.getId() );
            out.write("\">\r\n<table valign=\"top\" width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"8\" cellspacing=\"0\" class=\"docBox\">\r\n  <tr>\r\n  <td width=\"100%\" valign=\"top\">\r\n   <table width=\"100%\" border=\"0\" cellpadding=\"2\" cellspacing=\"0\">\r\n  <input type=\"hidden\" name=\"bodyId\" value=\"");
            out.print(bpo.getId() );
            out.write("\">  \r\n  <tr>\r\n    <td width=\"40\">标题：</td>\r\n    <td height=\"22\">");
            out.print(title );
            out.write("</td>\r\n  </tr>\r\n  <tr>\r\n  \t<td height=\"12\" nowrap></td>\r\n\t<td>\r\n\t   ");

	    boolean canModify=true;
	    String buttonName="上传附件";
           String tableName = "co_attach_table";
           String fileName = "attachName";
           String saveName = "attachSaveName";
           String path = "cooperate";
           String fileMaxSize = "0";
           String fileMaxNum = "0";
           String fileType = "";
           int fileMaxWidth = 0;
           int fileMaxHeight = 0;
           int fileMinWidth = 0;
           int fileMinHeight = 0;
           
            out.write("\r\n           ");
            out.write("\r\n\r\n\r\n\r\n<script>\r\nvar allAcc=new Array();\r\nvar singleAcc=new Array(4);\r\n\r\n</script>\r\n\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"");
            out.print(tableName);
            out.write("\" style=\"table-layout:fixed;\">\r\n\t");

	 if(SystemCommon.getFujianWatchType().equals("1")){
		 System.out.println("realFileArray.length="+realFileArray);
		 
            out.write("\r\n    <tr ");
            out.print(canModify&&((realFileArray!=null&&realFileArray.length ==0)||realFileArray==null)?"":"style='display:none'");
            out.write(">\r\n        <td height=\"25\"><span style=\"cursor:pointer;color:1e5494;text-decoration:underline\" onclick=\"javascript:addAccessory('");
            out.print(((path.indexOf(",")>0)?path.substring(path.indexOf(",")+1):path));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileName);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(saveName);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(tableName);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMaxSize);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMaxNum);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileType);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMinWidth);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMinHeight);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMaxWidth);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMaxHeight);
            out.write("');\"><img src='/jsoa/images/fj2.gif' align='absmiddle'>");
            out.print(buttonName );
            out.write("</span>\r\n\t        <div id=\"meet\" style=\"display:none;\">\r\n\t\t\t\t<span>（附件含活动/会议期间的日程安排、会议简介、主要参加人员等相关信息）</span>\r\n\t        </div>\r\n        </td>\r\n    </tr>\r\n     ");

	 }else{
		 
            out.write("\r\n\t\t<tr ");
            out.print(canModify?"":"style='display:none'");
            out.write(">\r\n        <td height=\"25\"><span style=\"cursor:pointer;color:1e5494;text-decoration:underline\" onclick=\"javascript:addAccessory('");
            out.print(((path.indexOf(",")>0)?path.substring(path.indexOf(",")+1):path));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileName);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(saveName);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(tableName);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMaxSize);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMaxNum);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileType);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMinWidth);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMinHeight);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMaxWidth);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileMaxHeight);
            out.write("');\"><img src='/jsoa/images/fj2.gif' align='absmiddle'>");
            out.print(buttonName );
            out.write("</span>\r\n\t        <div id=\"meet\" style=\"display:none;\">\r\n\t\t\t\t<span>（附件含活动/会议期间的日程安排、会议简介、主要参加人员等相关信息）</span>\r\n\t        </div>\r\n        </td>\r\n    </tr> \r\n\t");

	 }
	
            out.write("\r\n\t\r\n    <tr id=\"");
            out.print(tableName);
            out.write("_tr\">\r\n        <td id=\"");
            out.print(tableName);
            out.write("_td\" style=\"white-space:normal;word-wrap:break-word;word-break:break-all;font-size: 12px;text-align:left;\">\r\n            ");

            if (realFileArray != null && realFileArray.length > 0 ) {
            	
                //取历史附件的大小
                String hisPath=path;
                if(path.indexOf(",")>0){
                	hisPath=path.substring(0,path.indexOf(","));
                	path=path.substring(path.indexOf(",")+1);
                	
                }
                if(SystemCommon.getFujianWatchType().equals("0")){
                com.js.util.util.UploadFile upFile=new com.js.util.util.UploadFile();
       			for(int jj = 0; jj < realFileArray.length; jj ++){
       				if(!"".equals(realFileArray[jj]) && saveFileArray[jj]!=null){
					 String  docSaveName="";
				  docSaveName=saveFileArray[jj];	
	        	  String accSizeStr="("+upFile.getFileSize(docSaveName)+")";
	        	  if(docSaveName.indexOf("_")<0){
	        		  accSizeStr="";
	        	  }
				  //----------------------------------------
                
            out.write("                \r\n                 <span id=\"sp_");
            out.print(saveFileArray[jj].indexOf(".")>0?saveFileArray[jj].substring(0, saveFileArray[jj].indexOf(".")):saveFileArray[jj]);
            out.write("\" style=\"color:blue;cursor:pointer\" \r\n                 onclick=\"JSMainWinOpen4('/jsoa/download.jsp?");
            out.print(com.js.util.util.BASE64.BASE64EncoderNoBR("FileName="+saveFileArray[jj]+"&name="+realFileArray[jj]+"&path="+hisPath+"&edit="+(canModify?"1":"0")));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(com.js.util.config.SystemCommon.getFileShowUse()==1?"showPage":"downloadIframe" );
            out.write("','','status=no,menubar=0,scrollbars=1,locations=0,width=700,height=600,resizable=yes','800','');\"><img src=\"/jsoa/images/fj2.gif\" align=\"absmiddle\">");
            out.print(realFileArray[jj]);
            out.write("               \r\n                <input type=\"hidden\" id=\"");
            out.print(saveName);
            out.write("\" name=\"");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(saveFileArray[jj]);
            out.write("\"><input type=\"hidden\" id=\"");
            out.print(fileName);
            out.write("\" name=\"");
            out.print(fileName);
            out.write("\" value=\"");
            out.print(realFileArray[jj]);
            out.write("\"><input type=\"hidden\" id=\"");
            out.print(saveName);
            out.write("size\" name=\"");
            out.print(saveName);
            out.write("size\" value=\"0\">");
            out.print(accSizeStr);
            out.write("&nbsp;</span>");
if(canModify){
            out.write("<img src=\"/jsoa/images/del.gif\" style=\"cursor:pointer\" onclick=\"delaccessory('sp_");
            out.print(saveFileArray[jj].indexOf(".")>0?saveFileArray[jj].substring(0, saveFileArray[jj].indexOf(".")):saveFileArray[jj]);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(upFile.getFileLongSize());
            out.write("',this)\" align=\"absmiddle\">");
}
            out.write("&nbsp;&nbsp;\r\n                ");

       			}
                }
       			if(SystemCommon.getFujianBatchDownload().equals("1")&&realFileArray.length>1){
       				
            out.write("\r\n       \t\t\t\t <span id=\"sp_batch\" style=\"color:blue;cursor:pointer\" \r\n                 onclick=\"JSMainWinOpen4('/jsoa/downloadBatch.jsp?");
            out.print(com.js.util.util.BASE64.BASE64EncoderNoBR("FileName="+java.util.Arrays.toString(saveFileArray)+"&name="+java.util.Arrays.toString(realFileArray)+"&path="+hisPath+"&edit="+(canModify?"1":"0")));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(com.js.util.config.SystemCommon.getFileShowUse()==1?"showPage":"downloadIframe" );
            out.write("','','status=no,menubar=0,scrollbars=1,locations=0,width=700,height=600,resizable=yes','800','');\"><b>批量下载</b></span>              \r\n       \t\t\t");
}
                }else{
                	if(realFileArray.length == 1 && !canModify){
                		
            out.write("\r\n                \t\t<div style=\"cursor:pointer;\" onclick=\"JSMainWinOpen4('/jsoa/download.jsp?");
            out.print(com.js.util.util.BASE64.BASE64EncoderNoBR("FileName="+saveFileArray[0]+"&name="+realFileArray[0]+"&path="+hisPath+((canModify)?"&edit=1":"")));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(com.js.util.config.SystemCommon.getFileShowUse()==1?"showPage":"downloadIframe" );
            out.write("','','1100','680')\"><img src=\"/jsoa/images/fj2.gif\" align=\"absmiddle\">查看附件（<span id = \"sp_num");
            out.print(saveName);
            out.write('"');
            out.write('>');
            out.print( realFileArray.length);
            out.write("</span>）</div>\r\n                \t\t");

                	}else{
                		
            out.write("\r\n                \t    <div style=\"cursor:pointer;\" onclick=\"watchFujian('");
            out.print(saveName);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(fileName);
            out.write("')\"><img src=\"/jsoa/images/fj2.gif\" align=\"absmiddle\">查看附件（<span id = \"sp_num");
            out.print(saveName);
            out.write('"');
            out.write('>');
            out.print( realFileArray.length);
            out.write("</span>）</div>\r\n                \t\t");

                	}
                	
            out.write("\r\n                \t <div id='realFileForSave_");
            out.print(saveName);
            out.write("'>\r\n                \t ");

                	 String saveNameModify = "";
                	 String fileNameModify = "";
                	 for(int kk = 0; kk < realFileArray.length; kk++){
                		 saveNameModify += saveFileArray[kk]+"|";
                		 fileNameModify += realFileArray[kk]+"|";
                	 }
                	 saveNameModify = saveNameModify.substring(0,saveNameModify.length()-1);
                	 fileNameModify = fileNameModify.substring(0,fileNameModify.length()-1);
                	 
            out.write("\r\n                \t \t<input type=\"hidden\" id=\"");
            out.print(saveName);
            out.write("\" name=\"");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(saveNameModify);
            out.write("\">\r\n                \t    <input type=\"hidden\" id=\"");
            out.print(fileName);
            out.write("\" name=\"");
            out.print(fileName);
            out.write("\" value=\"");
            out.print(fileNameModify);
            out.write("\">\r\n                \t    <input type=\"hidden\" id=\"hisPath\" name=\"hisPath\" value=\"");
            out.print(hisPath);
            out.write("\">\r\n                \t </div>\r\n                \t");

                	
                }
            }
            
            out.write("\r\n        </td>\r\n    </tr>\r\n</table>\r\n<input type=\"hidden\" name=\"saveFileNameTemp_0_1\" value=\"\">\r\n<!-- 上传使用 -->\r\n<input type=\"hidden\" id=\"uploadPath_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(((path.indexOf(",")>0)?path.substring(path.indexOf(",")+1):path));
            out.write("\">\r\n<input type=\"hidden\" id=\"uploadFileName_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(fileName);
            out.write("\">\r\n<input type=\"hidden\" id=\"uploadSaveName_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(saveName);
            out.write("\">\r\n<input type=\"hidden\" id=\"uploadTableName_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(tableName);
            out.write("\">\r\n<input type=\"hidden\" id=\"uploadFileSize_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(fileMaxSize);
            out.write("\">\r\n<input type=\"hidden\" id=\"uploadFileNum_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(fileMaxNum);
            out.write("\">\r\n<input type=\"hidden\" id=\"uploadFileType_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(fileType);
            out.write("\">\r\n<input type=\"hidden\" id=\"uploadFileMinWidth_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(fileMinWidth);
            out.write("\">\r\n<input type=\"hidden\" id=\"uploadFileMinHeight_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(fileMinHeight);
            out.write("\">\r\n<input type=\"hidden\" id=\"uploadFileMaxWidtht_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(fileMaxWidth);
            out.write("\">\r\n<input type=\"hidden\" id=\"uploadFileMaxHeight_");
            out.print(saveName);
            out.write("\" value=\"");
            out.print(fileMaxHeight);
            out.write("\">\r\n<table style=\"display:none\">\r\n   <tr>\r\n       <td>\r\n           <iframe id=\"delFile\" name=\"delFile\" src=\"\"></iframe>\r\n           <input type=\"hidden\" name=\"deletedFileNames\" id=\"deletedFileNames\" value=\"\">\r\n\t\t   <input type=\"hidden\" name=\"allAttachSize\" id=\"allAttachSize\" value=\"0\">\r\n        </td>\r\n   </tr>\r\n</table>\r\n<iframe name=\"downloadIframe\" style=\"display:none;\"></iframe>\r\n<script language =\"javascript\">\r\nif(document.getElementById(\"meetingfile\")){\r\n\tvar val=document.getElementById(\"meetingfile\").value;\r\n\tif(val=='meeting'){\r\n\t\t");
if("landaedu".equals(SystemCommon.getCustomerName())){
            out.write("\r\n\t\t\tdocument.getElementById(\"meet\").style.display=\"\";\r\n\t\t");
}
            out.write("\r\n\t}\r\n}\r\nvar childWindow;\r\nfunction addAccessory(path,fileName,saveName,tableName,fileSize,fileNum,fileType,fileMinWidth,fileMinHeight,fileMaxWidth,fileMaxHeight){\r\n    var len=0;\r\n    var obj=eval(\"document.all.\"+saveName);\r\n    if(obj){\r\n        if(obj.length){\r\n            len=obj.length;\r\n        }else{\r\n            len=1;\r\n        }\r\n    }else{\r\n        len=0;\r\n    }\r\n    try{\r\n\t\tchildWindow.close();\r\n\t}catch(e){\r\n\t}\r\n    var wleft=window.screenLeft;\r\n\tvar wtop=window.screenTop;\r\n\t\r\n    if(fileNum==\"0\" || len<fileNum){\r\n\t\t\r\n        \r\n        childWindow=window.open(\"/jsoa/public/jsp/smartUpload.jsp?path=\"+path+\"&fileName=\"+fileName+\"&saveName=\"+saveName+\"&tableName=\"+tableName+\"&fileMaxSize=\"+fileSize+\"&fileMaxNum=\"+fileNum+\"&fileType=\"+fileType+\"&fileMinHeight=\"+fileMinHeight+\"&fileMinWidth=\"+fileMinWidth+\"&fileMaxHeight=\"+fileMaxHeight+\"&fileMaxWidth=\"+fileMaxWidth,'");
            out.print(Resource.getValue(session.getAttribute("org.apache.struts.action.LOCALE").toString(), "common", "comm.upload"));
            out.write("','menubar=0,scrollbars=0,left='+wleft+',top='+wtop+',width=450,height=250,resizable=no');\r\n        \r\n\t\tchildWindow.focus();\r\n    }else{\r\n        alert(\"");
            out.print(Resource.getValue(session.getAttribute("org.apache.struts.action.LOCALE").toString(), "common", "comm.maxuplaodattachment"));
            out.write("\"+fileNum+\"");
            out.print(Resource.getValue(session.getAttribute("org.apache.struts.action.LOCALE").toString(), "common", "comm.attachment"));
            out.write("\");\r\n    }\r\n}\r\nfunction delaccessory(spId, accessorySize, imgObj) {\r\n\tif(confirm(\"");
            out.print(Resource.getValue(session.getAttribute("org.apache.struts.action.LOCALE").toString(), "common", "comm.attremind2"));
            out.write("\")){\r\n\t\tvar sp = document.getElementById(spId);\r\n\t\tsp.innerHTML = \"\";\r\n\t\t//imgObj.removeNode();\r\n\t\tvar p = imgObj.parentElement;\r\n\t\tp.removeChild(imgObj);\r\n\t\t//document.getElementById(\"co_attach_table_td\").removeChild(imgObj);\r\n\t\t//imgObj.parentNode.parentNode.parentNode.removeChild(imgObj.parentNode.parentNode);\r\n\t\tif(document.all.accessorySize){\r\n\t\t\tdocument.all.accessorySize.value = parseInt(document.all.accessorySize.value) - parseInt(accessorySize);\r\n\t\t}\r\n\t}\r\n}\r\n\r\nfunction deleteAccessory(path){\r\n\tif(confirm(\"");
            out.print(Resource.getValue(session.getAttribute("org.apache.struts.action.LOCALE").toString(), "common", "comm.attremind2"));
            out.write("\")){\r\n\t\tvar delName=document.all.deletedFileNames.value;\r\n\t\tif(delName!=\"\"){\r\n\t\t\tdocument.all.delFile.src=\"/jsoa/public/jsp/deleteFile.jsp?delpath=\"+path+\"&delfiles=\"+delName;\r\n\t\t}\r\n\t}\r\n}\r\n\r\nfunction clearAccessory(table,path,saveName,fileName){\r\n    var obj=eval(\"document.all.\"+table+\".rows\");\r\n    for(var i=0;i<obj.length;i++){\r\n        if(eval(\"document.all.\"+saveName+\".value\")){\r\n            var temp=eval(\"document.all.\"+saveName+\".value\");\r\n            document.all.deletedFileNames.value=document.all.deletedFileNames.value+\",\"+temp;\r\n        }else{\r\n            var j=i-1;\r\n            var temp=eval(\"document.all.\"+saveName+\"[\"+j+\"].value\");\r\n            document.all.deletedFileNames.value=document.all.deletedFileNames.value+\",\"+temp;\r\n        }\r\n        //obj(i).removeNode(true);\r\n         eval(\"document.all.\"+table+\".deleteRow(\"+i+\")\");\r\n    }\r\n    deleteAccessory();\r\n}\r\n\r\nfunction watchFujian(saveid,Fileid){\r\n\tvar hisPath = document.getElementById(\"hisPath\").value;\r\n\tvar saveName = document.getElementById(saveid).value;\r\n");
            out.write("\tvar fileName = document.getElementById(Fileid).value;\r\n\tvar edit=\"\";\r\n\tif(");
            out.print(canModify);
            out.write("){\r\n\t\tedit = \"&edit=1\";\r\n\t}\t\r\n\tvar url =  new Base64().encode(encodeURI(\"FileName=\"+saveName+\"&name=\"+fileName+\"&saveName=\"+saveid+\"&path=\"+hisPath+edit));\r\n\t\r\n\t//传递url的值到session中\r\n\tvar http_request = false;\r\n   \r\n    if(window.XMLHttpRequest) {\r\n        http_request = new XMLHttpRequest();\r\n        if (http_request.overrideMimeType) {\r\n            http_request.overrideMimeType('text/xml');\r\n        }\r\n    } else if (window.ActiveXObject) { \r\n        try {\r\n            http_request = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n        } catch (e) {\r\n            try {\r\n                http_request = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n            } catch (e) {}\r\n        }\r\n    }\r\n    if (!http_request) { \r\n        window.alert(\"不能创建XMLHttpRequest对象实例.\");\r\n        return false;\r\n    }else{     \r\n        http_request.open(\"POST\", \"/jsoa/public/jsp/saveUrlData.jsp\", false);/*此处需同步执行*/\r\n        http_request.setRequestHeader(\"Content-Type\",\"application/x-www-form-urlencoded\");\r\n        http_request.send(\"putURL=\"+url);\r\n");
            out.write("    }\r\n    if (http_request.readyState == 4) { \r\n        if (http_request.status == 200) { \r\n        \tJSMainWinOpen4(\"/jsoa/public/jsp/doc_receivewatch.jsp\",'','','1100','680');\r\n        } else { /*页面不正常*/\r\n            alert(\"您所请求的页面有异常。\");\r\n        }\r\n    }\r\n\t\r\n}\r\n \r\n\r\n</script>\r\n<script   for=\"window\"   event=\"onbeforeunload\"> \r\ntry{\r\n\tchildWindow.close();\r\n}catch(e){\r\n}\r\n</script>  \r\n<script type=\"text/javascript\" src=\"/jsoa/js/base64ToAttach.js\"></script>\r\n<script src=\"/jsoa/js/util.js\"></script>");
            out.write("\r\n\t</td>\r\n   </tr>\r\n   <tr>\r\n        <td valign=top>正文：</td>\r\n\t\t<td valign=\"top\">\r\n\t\t\t<textarea name=\"content\" style=\"display:none\"></textarea>\r\n\t\t\t<INPUT type=\"hidden\" name=\"content1\">\r\n\t\t\t");
 if(com.js.util.util.BrowserJudge.isMSIE(request)) { 
            out.write("\r\n\t\t\t\t<IFRAME id=\"newedit\" src=\"/jsoa/public/edit/ewebeditor.htm?id=content1&style=coolblue&lang=");
            out.print(session.getAttribute("org.apache.struts.action.LOCALE"));
            out.write("\" frameborder=\"0\" scrolling=\"no\" width=\"100%\" height=\"330\"></IFRAME>\r\n\t\t\t");
 }else{
            out.write("\r\n\t\t\t\t<IFRAME id=\"newedit\" src=\"/jsoa/public/edit8/ewebeditor.htm?id=content1&style=coolblue&lang=");
            out.print(session.getAttribute("org.apache.struts.action.LOCALE"));
            out.write("\" frameborder=\"0\" scrolling=\"no\" width=\"100%\" height=\"330\"></IFRAME>\r\n\t\t\t");
}
            out.write("\t\t\t\r\n\t\t\t                                            \r\n\t\t</td>\r\n   </tr>\r\n\t<tr style=\"display:none\">\r\n\t     <td colspan=4>\r\n\t       <iframe id=\"tempIframe\" src=\"\"></iframe>\r\n\t       <div id=\"oldContent\">");
            out.print(content );
            out.write("</div>\r\n\t     </td>\r\n\t</tr>\r\n\t<tr>\r\n\t\t<td colspan=\"2\" height=\"45\" valign=\"bottom\">\r\n\t\t\t<input type=\"button\" class=\"btnButton4font\" onclick=\"javascript:save();\" value=\"保存\"/>\r\n\t\t\t<input type=\"button\" class=\"btnButton4font\" onclick=\"javascript:window.close();\" value=\"退出\"/>\r\n\t\t</td>\r\n\t</tr>\r\n\t</table>\r\n\t</td>\r\n\t</tr>\r\n\t<tr>\r\n\t<td>&nbsp;</td>\r\n\t</tr>\r\n</table>\r\n\r\n</form>\r\n\r\n</body>\r\n");
            int evalDoAfterBody = _jspx_th_html_005fhtml_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_html_005fhtml_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fhtml_005fhtml.reuse(_jspx_th_html_005fhtml_005f0);
        _jspx_th_html_005fhtml_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fhtml_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fhtml_005f0_reused);
      }
      out.write("\r\n<script>\r\nfunction loadHtmlEdit(){\r\n\t\r\n\t//document.all.newedit.src=\"/jsoa/public/edit/ewebeditor.htm?id=content1&style=coolblue&lang=");
      out.print(session.getAttribute("org.apache.struts.action.LOCALE"));
      out.write("\";\r\n\tsetTimeout(\"setHTMLContent()\",500);\r\n}\r\n\r\nfunction setHTMLContent(){\r\n\r\n\ttry{\r\n\t\tif(!document.all){\r\n\t\tdocument.all.newedit.readyState=\"complete\";\r\n\t\t}\r\n\t\tif(document.all.newedit.readyState!=\"complete\"){\r\n\t\t\tsetTimeout(\"setHTMLContent()\",300);\r\n\t\t\treturn;\r\n\t\t}\t\r\n\t");
 if(com.js.util.util.BrowserJudge.isMSIE(request)) { 
      out.write("\r\n\t\tnewedit.setHTML(document.all.oldContent.innerHTML);\r\n\t");
 }else{
      out.write("\r\n\t\tdocument.getElementById(\"newedit\").contentWindow.setHTML(document.all.oldContent.innerHTML)\r\n\t");
}
      out.write("\t\r\n\t\t\r\n\t\t\r\n\t}catch(e){\r\n\t}\r\n}\r\nfunction save(){\r\n     \r\n\t\r\n\t");
 if(com.js.util.util.BrowserJudge.isMSIE(request)) { 
      out.write("\r\n\t\tdocument.frm.content.value=newedit.getHTML();\r\n\t");
 }else{
      out.write("\r\n\t \tdocument.frm.content.value = document.getElementById(\"newedit\").contentWindow.getHTML()\r\n\t\r\n\t");
}
      out.write("\r\n\tvar content_=document.frm.content.value;\r\n\tcontent_=content_.replace(/\\s/g,\"\");\r\n\tif(content_==\"\"){\r\n      alert(\"内容不能为空！\");\r\n    }else{\r\n\tdocument.frm.submit();\r\n\t}\r\n}\r\n</script>\r\n<script src=\"/jsoa/js/util.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
