/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2023-01-06 09:44:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.js.oa.online.service.OnlineDB;
import com.js.util.config.SystemCommon;
import com.js.util.util.BrowserJudge;
import com.js.util.util.*;
import com.js.lang.Resource;
import com.js.util.config.SystemCommon;

public final class chat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/public/jsp/upload.jsp", Long.valueOf(1499751452000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.js.util.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.js.lang.Resource");
    _jspx_imports_classes.add("com.js.util.config.SystemCommon");
    _jspx_imports_classes.add("com.js.oa.online.service.OnlineDB");
    _jspx_imports_classes.add("com.js.util.util.BrowserJudge");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n\r\n");

response.setHeader("Cache-Control","no-store");
response.setHeader("Pragma","no-cache");
response.setDateHeader ("Expires", 0);

String single = SystemCommon.getChatSingle(); //是否只能发送给单人
String uesrId = request.getParameter("id");  //发送至用户ID
if(uesrId.indexOf("$")<0){//此处传的userId含有$,则不再验证是否为数字
	if(!ParameterFilter.isNumber(uesrId) ){
		try{
			response.sendRedirect(request.getContextPath()+"/public/jsp/inputerror.jsp");
		}catch(Exception ex){
			
		}
	}	
}

String userName ="";
String idstr="";
if(uesrId.indexOf("$")<0){
	if(!"".equals(uesrId)){
		OnlineDB onlineDB = new OnlineDB();
		userName = onlineDB.getName(uesrId);
		
		if (userName == null) {
			userName = "";
		}
		userName = userName+",";
		idstr="$"+uesrId+"$";
	}else{
		userName ="";
		idstr="";
	}
	
}else{
	idstr = uesrId;
	userName = request.getParameter("userName");
	userName=java.net.URLDecoder.decode(userName, "UTF-8");//火狐乱码处理
}


      out.write("\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n<html>\r\n\t<head>\t\r\n\t\t<title>发送消息</title>\r\n\t\t<SCRIPT language=\"javascript\" src=\"/jsoa/js/openEndow.js\"></SCRIPT>\r\n\t\t<link href=\"/jsoa/skin/");
      out.print(session.getAttribute("skin"));
      out.write("/style-");
      out.print(session.getAttribute("browserVersion"));
      out.write(".css\" rel=\"stylesheet\" type=\"text/css\" />\r\n\t</head>\r\n\r\n\t<body style=\"font-family: '宋体'; font-size: 12px; margin: 0px;\">\r\n\t\r\n\t<form name=\"myForm\" action=\"/jsoa/ChatAction.do\"  method=\"post\">\r\n\t\t<table width=\"428\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n\t\t\t<input type=\"hidden\" name=\"action\" value=\"sendChat\">\r\n\t\t\t\t\r\n\t\t\t<tr>\r\n\t\t\t\t<td height=\"40\" align=\"left\" valign=\"bottom\"\r\n\t\t\t\t\tstyle=\"background-image: url(/jsoa/images/ss.gif); color: #091B72; font-size: 14px; font-weight: bold;\">\r\n\t\t\t\t\t&nbsp;&nbsp;发送消息给：\r\n\t\t\t\t\t<span id=\"tospan\" style=\"\">\r\n\t\t\t\t\t  <input name=\"chatTo\" id=\"chatTo\" readonly=\"readonly\" style=\"overflow: hidden; width: 70%\" class=\"inputTextarea\" type=\"_moz\" title=\"请点击选择\" onclick=\"openEndow('chatToId','chatTo',myForm.chatToId.value,myForm.chatTo.value,'user','");
      out.print(single );
      out.write("','user','");
      out.print(session.getAttribute("browseRange"));
      out.write("')\" value=\"");
      out.print(userName );
      out.write("\"></input>\t\t\t\t\t\t\t \r\n\t\t\t\t\t  <input type=\"hidden\" name=\"chatToId\" id=\"chatToId\" value=\"");
      out.print(idstr);
      out.write("\">\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t</span>\r\n\t\t\t\t</td>\r\n\t\t\r\n\t\t\t\t<tr>\r\n\t\t\t\t<td height=\"115\" align=\"center\" valign=\"bottom\">\r\n\t\t\t\t\t<textarea id=\"chatContent\" name=\"chatContent\" rows=\"");
      out.print((BrowserJudge.isFirefox(request)?"4":"6"));
      out.write("\" style=\"width: 398px;\"></textarea>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\r\n\t\t\t\t<td height=\"85\" align=\"left\" valign=\"top\" style=\"color: #0000FF;padding-left: 12px;\" width=\"400\">\r\n\t\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n\t\t\t\t\t\r\n\t\t\t\t\t");

						java.util.Map sysMap = com.js.system.util.SysSetupReader.getInstance().getSysSetupMap(session.getAttribute("domainId") == null ? "0": session.getAttribute("domainId").toString());
					
						String path = "chat";//保存附件路径
						String tableName = "chatdisplaytable";//显示附件列表的table名
						String fileName = "chatFileName";//保存文件名的控件
						String saveName = "chatSaveName";//保存上传文件存储名的控件
						int fileMaxSize = 0; //附件大小(以字节为单位)，一旦设置上传的附件大小将不能大于设置值 0为不限制大小
						int fileMaxNum = 0; //可上传附件的最大个数 0为不限制个数
						int fileMaxWidth = 0; //可以上传的附件的最大宽度
						int fileMaxHeight = 0; //可以上传的附件的最大高度
						int fileMinWidth = 0; //可以上传的附件的最小宽度
						int fileMinHeight = 0; //可以上传的附件的最小宽度
						String fileType = ""; //文件类型 如 fileType="bmp,gif";
						String buttonName="上传附件";
					
      out.write("\r\n\t\t\t\t\t\r\n\t\t\t\t\t");
      out.write("\r\n\r\n\r\n");

request.setCharacterEncoding("GBK"); 

      out.write("\r\n<table width=\"420\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"");
      out.print(tableName);
      out.write("\" style=\"table-layout:fixed;\">\r\n    <tr>\r\n        <td height=\"40\"><span style=\"cursor:pointer;color:1e5494;text-decoration:underline\" onclick=\"javascript:addAccessory('");
      out.print(path);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(fileName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(saveName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(tableName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(fileMaxSize);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(fileMaxNum);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(fileType);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(fileMinWidth);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(fileMinHeight);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(fileMaxWidth);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(fileMaxHeight);
      out.write("');\"><img src='/jsoa/images/fj2.gif' align='absmiddle'>");
      out.print(buttonName );
      out.write("</span>\r\n        <div id=\"meet\" style=\"display:none;\">\r\n\t\t\t<span>（附件含活动/会议期间的日程安排、会议简介、主要参加人员等相关信息）</span>\r\n        </div>\r\n        </td>\r\n    </tr>\r\n    <tr id=\"");
      out.print(tableName);
      out.write("_tr\">\r\n        <td id=\"");
      out.print(tableName);
      out.write("_td\" style=\"white-space:normal;word-wrap:break-word;word-break:break-all;font-size: 12px\"></td>\r\n    </tr>\r\n</table>\r\n<input type=\"hidden\" name=\"saveFileNameTemp_0_1\" value=\"\">\r\n<table style=\"display:none\">\r\n   <tr>\r\n       <td><iframe id=\"delFile\" name=\"delFile\" src=\"\"></iframe></td>\r\n\t   <input type=\"hidden\" name=\"allAttachSize\" value=\"0\">\r\n   </tr>\r\n</table>\r\n<script language =\"javascript\">\r\nif(document.getElementById(\"meetingfile\")){\r\n\tvar val=document.getElementById(\"meetingfile\").value;\r\n\tif(val=='meeting'){\r\n\t\t");
if("landaedu".equals(SystemCommon.getCustomerName())){
      out.write("\r\n\t\t\tdocument.getElementById(\"meet\").style.display=\"\";\r\n\t\t");
}
      out.write("\r\n\t}\r\n}\r\nvar childWindow;\r\n\r\nfunction addAccessory(path,fileName,saveName,tableName,fileSize,fileNum,fileType,fileMinWidth,fileMinHeight,fileMaxWidth,fileMaxHeight){\r\n    var len=0;\r\n    var obj=eval(\"document.all.\"+saveName);\r\n    if(obj){\r\n        if(obj.length){\r\n            len=obj.length;\r\n        }else{\r\n            len=1;\r\n        }\r\n    }else{\r\n        len=0;\r\n    }\r\n\ttry{\r\n\t\tchildWindow.close();\r\n\t}catch(e){\r\n\t}\r\n\t\r\n\tvar wleft=window.screenLeft;\r\n\tvar wtop=window.screenTop;\r\n\t\t\r\n    if(fileNum==\"0\" || len<fileNum){\r\n        \r\n        childWindow=window.open(\"/jsoa/public/jsp/smartUpload.jsp?path=\"+path+\"&fileName=\"+fileName+\"&saveName=\"+saveName+\"&tableName=\"+tableName+\"&fileMaxSize=\"+fileSize+\"&fileMaxNum=\"+fileNum+\"&fileType=\"+fileType+\"&fileMinHeight=\"+fileMinHeight+\"&fileMinWidth=\"+fileMinWidth+\"&fileMaxHeight=\"+fileMaxHeight+\"&fileMaxWidth=\"+fileMaxWidth,'");
      out.print(Resource.getValue(session.getAttribute("org.apache.struts.action.LOCALE").toString(), "common", "comm.upload"));
      out.write("','menubar=0,scrollbars=0,left='+wleft+',top='+wtop+',width=450,height=250,resizable=no');\r\n        \t\t\r\n\t\tchildWindow.focus();\r\n\r\n    }else{\r\n        alert(\"");
      out.print(Resource.getValue(session.getAttribute("org.apache.struts.action.LOCALE").toString(), "common", "comm.maxuplaodattachment"));
      out.write("\"+fileNum+\"");
      out.print(Resource.getValue(session.getAttribute("org.apache.struts.action.LOCALE").toString(), "common", "comm.attachment"));
      out.write("\");\r\n    }\r\n}\r\n\r\nfunction delaccessory(spId, accessorySize, imgObj) {\r\n\tif(confirm(\"");
      out.print(Resource.getValue(session.getAttribute("org.apache.struts.action.LOCALE").toString(), "common", "comm.attremind2"));
      out.write("\")){\r\n\t\tvar sp = document.getElementById(spId);\r\n\t\tsp.innerHTML = \"\";\r\n\t\timgObj.parentNode.removeChild(imgObj);\r\n\t\tif(document.all.accessorySize){\r\n\t\t\tdocument.all.accessorySize.value = parseInt(document.all.accessorySize.value) - parseInt(accessorySize);\r\n\t\t}\r\n\t}\r\n}\r\n/*\r\nfunction delaccessory(id,table,path,fileName,saveName,accessorySize){\r\n    if(confirm(\"您确定删除该附件吗?点确定删除！\")){\r\n        var del=\"A\"+id;\r\n        var obj=eval(\"document.all.\"+table+\".rows\");\r\n        for(var i=0;i<obj.length;i++){\r\n            if(obj(i).cells(0).id==del){\r\n                if(eval(\"document.all.\"+saveName+\".value\")){\r\n                    var temp=eval(\"document.all.\"+saveName+\".value\");\r\n                    document.all.delFile.src=\"/jsoa/public/jsp/deleteFile.jsp?delpath=\"+path+\"&delfiles=\"+temp;\r\n                }else{\r\n                    var j=i-1;\r\n                    var temp=eval(\"document.all.\"+saveName+\"[\"+j+\"].value\");\r\n                    document.all.delFile.src=\"/jsoa/public/jsp/deleteFile.jsp?delpath=\"+path+\"&delfiles=\"+temp;\r\n");
      out.write("                }\r\n                obj(i).removeNode(true);\r\n            }\r\n        }\r\n\r\n        if(document.all.accessorySize){\r\n            document.all.accessorySize.value = parseInt(document.all.accessorySize.value) - parseInt(accessorySize);\r\n        }\r\n    }\r\n}\r\n*/\r\n\r\n\r\n\r\nfunction clearAccessory(table,path,saveName,fileName){\r\n   /*\r\n    var obj=eval(\"document.all.\"+table+\".rows\");\r\n   var delfiles=\"\";\r\n   for(var i=obj.length-1;i>0;i--){\r\n       if(eval(\"document.all.\"+saveName+\".value\")){\r\n           var temp=eval(\"document.all.\"+saveName+\".value\");\r\n           delfiles+=temp+\",\";\r\n        }else{\r\n            var j=i-1;\r\n            var temp=eval(\"document.all.\"+saveName+\"[\"+j+\"].value\");\r\n            delfiles+=temp+\",\";\r\n        }\r\n        obj(i).removeNode(true);\r\n    }\r\n    */\r\n    eval(\"document.all.\" + table + \"_td.innerHTML=''\");\r\n//    document.all.\"+table\r\n//    document.all.delFile.src=\"/jsoa/public/jsp/deleteFile.jsp?delpath=\"+path+\"&delfiles=\"+delfiles;\r\n}\r\n</script>\r\n\r\n<script   for=\"window\"   event=\"onbeforeunload\"> \r\n");
      out.write("try{\r\n\tchildWindow.close();\r\n}catch(e){\r\n}\r\n</script>   \r\n");
      out.write("\t\t\t\t\t\r\n\t\t\t\t\t</td>\t\t\t\t\t\r\n\t\t\t\t\t<input type=\"hidden\"  id=\"accessorySize\" name=\"accessorySize\" value=\"");
      out.print(request.getAttribute("accessorySize")==null?"0":request.getAttribute("accessorySize"));
      out.write("\">\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td height=\"43\" align=\"right\" valign=\"middle\"\r\n\t\t\t\t\tstyle=\"background-image: url(/jsoa/images/dhh.gif)\">\r\n\t\t\t\t\t<input type=\"button\" class=\"btnButton2font\" style=\"cursor:pointer\" name=\"Submit\" value=\" 发 送 \" onClick=\"javascript:send();\"  />\r\n\t\t\t\t\t&nbsp;&nbsp;\r\n\t\t\t\t\t<input type=\"button\" class=\"btnButton2font\" style=\"cursor:pointer\" name=\"\" value=\" 取 消 \" onClick=\"javascript:window.close();\" />\r\n\t\t\t\t\t&nbsp;&nbsp;\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t\t</form>\r\n\t</body>\r\n</html>\r\n<script type=\"text/javascript\">\r\n     function send(){\t       \r\n\t   var content=document.myForm.chatContent.value;  \r\n\t   \tvar senduser=document.myForm.chatTo.value;\r\n\t\t\r\n\r\n\t   if(content.replace(/^\\s+|\\s+$/g, '')==\"\") {\r\n\t      alert(\"发送内容不能为空！\");\r\n\t      document.myForm.content.focus();  \r\n\t      return false;\r\n\t    }  \r\n\t    if(content.length>500){\r\n\t      alert(\"发送内容不能大于500个字符！\");\t \r\n\t      document.myForm.content.focus();  \r\n\t      return false;\r\n\t    } \r\n  \t\t   if(senduser.replace(/^\\s+|\\s+$/g, '')==\"请点击选择\" ){\r\n");
      out.write("\t   \t\t\t\t\t\t\r\n\t      alert(\"发送人不能为空\");\r\n\t      return false;\r\n\t   }  \r\n\t   document.myForm.submit();\r\n }\r\n</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
