/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2023-01-06 09:44:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.kq.szgt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import com.js.util.util.BrowserJudge;
import com.js.system.manager.service.ManagerService;

public final class kq_005freport_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-nested.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/pager-taglib.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-tiles.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-logic.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/public/page/pager.jsp", Long.valueOf(1499751452000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-html.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-template.tld", Long.valueOf(1499751390000L));
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-bean.tld", Long.valueOf(1499751390000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.js.util.util.BrowserJudge");
    _jspx_imports_classes.add("com.js.system.manager.service.ManagerService");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fpager_0026_005furl_005fscope_005fmaxPageItems_005fmaxIndexPages_005fitems_005fisOffset_005findex_005fexport;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fparam_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005findex_0026_005fexport;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fpage;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005ffirst;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fprev;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fpages;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005fnext;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpg_005flast_0026_005fexport;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fpg_005fpager_0026_005furl_005fscope_005fmaxPageItems_005fmaxIndexPages_005fitems_005fisOffset_005findex_005fexport = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fparam_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005findex_0026_005fexport = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fpage = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005ffirst = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fprev = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fpages = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005fnext = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpg_005flast_0026_005fexport = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fpg_005fpager_0026_005furl_005fscope_005fmaxPageItems_005fmaxIndexPages_005fitems_005fisOffset_005findex_005fexport.release();
    _005fjspx_005ftagPool_005fpg_005fparam_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fpg_005findex_0026_005fexport.release();
    _005fjspx_005ftagPool_005fpg_005fpage.release();
    _005fjspx_005ftagPool_005fpg_005ffirst.release();
    _005fjspx_005ftagPool_005fpg_005fprev.release();
    _005fjspx_005ftagPool_005fpg_005fpages.release();
    _005fjspx_005ftagPool_005fpg_005fnext.release();
    _005fjspx_005ftagPool_005fpg_005flast_0026_005fexport.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");

String currentMonth=request.getAttribute("currentMonth").toString();

SimpleDateFormat formatVal = new SimpleDateFormat("yyyyMM");
SimpleDateFormat formatTxt = new SimpleDateFormat("yyyy年MM月");

String userName=request.getParameter("userName");

String searchOrgName = request.getAttribute("searchOrgName")==null?(null==request.getParameter("searchOrgName")?"":request.getParameter("searchOrgName")):request.getAttribute("searchOrgName").toString();
String searchOrgId = request.getAttribute("searchOrgId")==null?(null==request.getParameter("searchOrgId")?"":request.getParameter("searchOrgId")):request.getAttribute("searchOrgId").toString();

if(userName==null || "null".equals(userName)){
	userName="";
}
String caculating=request.getAttribute("caculating")==null?"":request.getAttribute("caculating").toString();
//caculating="1";

      out.write("\r\n<html>\r\n<head>\r\n<META HTTP-EQUIV=\"pragma\" CONTENT=\"no-cache\"> \r\n<META HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache, must-revalidate\"> \r\n<META HTTP-EQUIV=\"expires\" CONTENT=\"Wed, 26 Feb 1997 08:21:57 GMT\">\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=GBK\">\r\n<title>考勤统计</title>\r\n<link href=\"skin/");
      out.print(session.getAttribute("skin"));
      out.write("/style-");
      out.print(session.getAttribute("browserVersion"));
      out.write(".css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<link rel=stylesheet type=\"text/css\" href=\"/jsoa/public/date_picker/DateObject2.css\">\r\n<SCRIPT language=javascript src=\"/jsoa/js/openEndow.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/DateObject.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/DatePicker.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/editlib.js\"></SCRIPT>\r\n<SCRIPT language=javascript src=\"/jsoa/public/date_picker/tree.js\"></SCRIPT>\r\n<script src=\"/jsoa/js/js.js\" language=\"javascript\"></script>\r\n<script src=\"/jsoa/js/util.js\"></script>\r\n<SCRIPT language=javascript src=\"/jsoa/js/openEndow.js\"></SCRIPT>\r\n</head>\r\n<body  class=\"MainFrameBox\" >\r\n<table id=\"listtable\" width=\"100%\" border=0 cellpadding=\"0\" cellspacing=\"0\" ");
if("1".equals(caculating)){out.print("style=\"display:none\"");} 
      out.write(">\r\n<tr>\r\n<td>\r\n<iframe id=\"myIframe\" name=\"myIframe\" style=\"display:none;\"></iframe>\r\n<form name=\"frm1\" action=\"SKqReportAction.do?action=list\" method=\"post\">\r\n<table width=\"100%\" border=\"0\" id=\"searchtable\"  style=\"display:none;\"  align=\"center\" cellpadding=\"1\" cellspacing=\"1\" class=\"searchbar\">\r\n\r\n\t <tr>\r\n\t  <td width=\"20\" rowspan=\"2\"></td>\r\n\t  <td width=\"10%\"   id=\"userTR\" >人员：</td>\r\n\t <td width=\"30%\"  id=\"userTR1\"   >\r\n\t\t<input type=\"text\" name=\"userName\" id=\"userName\" value=\"");
      out.print(userName);
      out.write("\" class=\"inputText\">\r\n\t</td>\r\n\t  <td  width=\"10%\"   id=\"orgTR\" > 部门：</td>\r\n\t <td  width=\"30%\"   > \r\n      <input type=\"hidden\" id=\"searchOrgId\" name=\"searchOrgId\" value=\"");
      out.print(searchOrgId );
      out.write("\"/>\r\n      <input type=\"text\" class=\"inputtext\" id=\"searchOrgName\" name=\"searchOrgName\" value=\"");
      out.print(searchOrgName );
      out.write("\" readonly onClick=\"javascript:selectEndowOrg('searchOrgId','searchOrgName','org','yes','org','");
      out.print(session.getAttribute("browseRange").toString() );
      out.write("');\" size=\"20\"/>\r\n\t\r\n\t</td>\t\r\n\t</tr>\r\n\t<tr>\r\n\t  <td>\r\n\t\t 时间：\r\n\t  </td>\r\n\t  <td colspan=\"3\">\r\n\t\t<select name=\"currentMonth\" id=\"currentMonth\">\r\n\t\t   ");

		   Calendar calendar=Calendar.getInstance();
		   
		   int tempYear=calendar.get(Calendar.YEAR);
		   int tempMonth=calendar.get(Calendar.MONTH);

		   calendar.set(Calendar.YEAR,calendar.get(Calendar.YEAR)-2);
		   calendar.set(Calendar.MONTH,0);
		   
		   String val,txt;
		
		   while(tempYear>calendar.get(Calendar.YEAR) || (tempYear==calendar.get(Calendar.YEAR) && tempMonth>=calendar.get(Calendar.MONTH))){
			   val=formatVal.format(calendar.getTime());
			   txt=formatTxt.format(calendar.getTime());
		   
      out.write("\r\n\t\t   <option value=\"");
      out.print(val);
      out.write('"');
      out.write(' ');
if(val.equals(currentMonth)){out.print("selected");}
      out.write('>');
      out.print(txt );
      out.write("</option>\r\n\t\t   ");

		   		calendar.add(Calendar.MONTH,1);
		   } 
		   
      out.write("\r\n\t\t</select>\r\n\t  </td>\r\n\t  <td align=\"right\" colspan=2>\r\n\t      <button class=\"btnButton2Font\" onClick=\"searcher();\">查询</button>\r\n\t\t  <button class=\"btnButton2Font\" onClick=\"unsearcher();\">重置</button>\r\n\t  </td>\r\n\t  <td width=\"16\" rowspan=\"2\"></td>\r\n\t</tr>\r\n</table>\r\n</form>\r\n<table width=\"100%\" height=\"25\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n  <tr>\r\n   <td width=\"45%\" scope=\"col\">\t\r\n     <div valign=\"bottom\" >&nbsp;\r\n     ");

     int currentYear=Integer.parseInt(currentMonth.substring(0,4));
     int currentMon=Integer.parseInt(currentMonth.substring(4,6));
     Calendar cal=Calendar.getInstance();
     cal.set(Calendar.YEAR,currentYear);
     cal.set(Calendar.MONTH,(currentMon-1));
     cal.set(Calendar.DATE,1);

     String currentMonthStr=formatTxt.format(cal.getTime());

     cal.add(Calendar.MONTH, -1);
     String preMonth=formatVal.format(cal.getTime());

     cal.add(Calendar.MONTH, 2);
     String nextMonth=formatVal.format(cal.getTime());
     
      out.write("\r\n     \t<a href=\"javascript:void(0);goMonth(");
      out.print(preMonth );
      out.write(");\" title=\"上月\"><img src=\"/jsoa/skin/");
      out.print(session.getAttribute("skin"));
      out.write("/images/prev.gif\" border=0 align=\"absmiddle\"/></a>&nbsp;\r\n\t\t  ");
      out.print(currentMonthStr );
      out.write("\r\n\t   <a href=\"javascript:void(0);goMonth(");
      out.print(nextMonth );
      out.write(");\" title=\"下月\"><img src=\"/jsoa/skin/");
      out.print(session.getAttribute("skin"));
      out.write("/images/next.gif\"  border=0 align=\"absmiddle\"/></a>&nbsp;\r\n\t  \r\n     </div>\r\n    </td>\r\n    <td align=\"right\"> \r\n    ");
if("1".equals(request.getAttribute("canCaculate"))){ 
      out.write("\r\n    ");
if("1".equals(request.getAttribute("dataLockStatus"))){ 
      out.write("\r\n    <font color=\"red\">本月数据已经锁定</font>\r\n    ");
}else{ 
      out.write(" \r\n    <input type=\"button\" id=\"hiddenCaculate\"  class=\"btnButton4Font\" onClick=\"dataLock()\" value=\"锁定数据\" />  \r\n    <input type=\"button\" id=\"hiddenCaculate\"  class=\"btnButton4Font\" onClick=\"reCaculate()\" value=\"重新计算\" />\r\n    ");
} 
      out.write("\r\n    ");
} 
      out.write("    \r\n    <input type=\"button\" id=\"hiddenSearch\"  class=\"btnButton4Font\" onClick=\"exportList()\" value=\"导出\" />\r\n\t<input type=\"button\" id=\"hiddenSearch1\"  class=\"btnButton4Font\" onClick=\"hidserch()\" value=\"查询\" />\r\n\t</td>\r\n </tr>\r\n</table>\r\n\r\n<table width=\"100%\"  border=\"1\" align=\"center\" cellpadding=\"1\" cellspacing=\"0\" style=\"font-size:14px;\" bordercolorlight=\"#000000\" bordercolordark=\"#FFFFFF\">\r\n\t<tr align=\"center\">\r\n\t\t<td width=\"15%\" rowspan=\"2\">部门</td>\r\n\t\t<td width=\"8%\" rowspan=\"2\">姓名</td>\r\n\t\t<td width=\"5%\"  rowspan=\"2\">迟到早退次数</td>\r\n\t\t<td width=\"5%\"  rowspan=\"2\">未打卡次数</td>\r\n\t\t<td width=\"5%\"  rowspan=\"2\">应出勤天数</td>\r\n\t\t<td width=\"5%\"  rowspan=\"2\">加班小时</td>\r\n\t\t<td width=\"5%\"  rowspan=\"2\">调休小时</td>\r\n\t\t\r\n\t\t<td width=\"30%\" colspan=\"6\">带薪休假(小时)</td>\r\n\t\t<td width=\"20%\" colspan=\"4\">不带薪休假(小时)</td>\r\n\t\t<td width=\"5%\" rowspan=\"2\">实际出勤天数</td>\r\n\t\t<td width=\"5%\" rowspan=\"2\">出差天数</td>\r\n\t\t<td width=\"5%\" rowspan=\"2\">剩余年假小时</td>\r\n\t\t<td width=\"15%\"  colspan=\"3\">累计(小时)</td>\t\t\r\n\t  </tr>\r\n\t  <tr align=\"center\">\r\n\t\t  <td height=\"40\" width=\"3%\">年假</td>\r\n");
      out.write("\t\t  <td width=\"3%\">病假</td>\r\n\t\t  <td width=\"3%\">工伤</td>\r\n\t\t  <td width=\"3%\">婚假</td>\r\n\t\t  <td width=\"3%\">产假</td>\r\n\t\t  <td width=\"3%\">丧假</td>\r\n\t\t  <td width=\"3%\">病假</td>\r\n\t\t  <td width=\"3%\">事假</td>\r\n\t\t  <td width=\"3%\">停工</td>\r\n\t\t  <td width=\"3%\">旷工</td>\r\n\t\t  <td width=\"3%\">年假</td>\r\n\t\t  <td width=\"3%\">不带薪病假</td> \r\n\t\t  <td width=\"3%\">事假</td> \r\n\t  </tr>\r\n  \r\n\t ");

	  String listClass="listTableLine1";
	  List list=(List)request.getAttribute("list");
	  if(list!=null){
		  for(int i=0;i<list.size();i++){
			  String[] obj=(String[])list.get(i);
			  listClass ="";// i%2!=0?"listTableLine2":"listTableLine1";
			  
      out.write("\r\n\t<tr>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[1] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[2] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[3] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[4] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[5] );
      out.write("</td>\t\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[8] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[9] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[10] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[11] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[12] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[13] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[14] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[15] );
      out.write("</td>\r\n\t\t\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[16] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[17] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[18] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[19] );
      out.write("</td>\r\n\t\t\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[6] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[7] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[20] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[21] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[22] );
      out.write("</td>\r\n\t\t<td class=\"");
      out.print(listClass);
      out.write('"');
      out.write('>');
      out.print(obj[23] );
      out.write("</td>\r\n\t</tr>\r\n\t\t\t  \r\n\t\t\t  ");

		  }
	  }
	  
      out.write("\r\n\t \r\n</table>\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"pagebar\">  \r\n  <tr>\r\n    <td>\r\n\t ");
String pagerURL = "/jsoa/SKqReportAction.do";
      out.write("\r\n     ");
      out.write("\r\n\r\n<div><table width=\"100%\" height=\"22\">\r\n  <tr>\r\n    <td height=\"22\" align=\"right\" width=\"100%\">\r\n");

String page_local = session.getAttribute("org.apache.struts.action.LOCALE").toString();
int recordCount=Integer.parseInt((String)request.getAttribute("recordCount"));
StringBuffer pager_query_string=new StringBuffer(pagerURL);

                int maxPageItems=Integer.parseInt((String)request.getAttribute("maxPageItems"));
				String pageParameters=(String)request.getAttribute("pageParameters");
                String[] paraArray=null;
                if(pageParameters!=null && !pageParameters.equals("null")){
                    paraArray=pageParameters.split(",");
                }
                
				if(recordCount>maxPageItems){
                
      out.write("\r\n                ");
      //  pg:pager
      com.jsptags.navigation.pager.PagerTag _jspx_th_pg_005fpager_005f0 = (com.jsptags.navigation.pager.PagerTag) _005fjspx_005ftagPool_005fpg_005fpager_0026_005furl_005fscope_005fmaxPageItems_005fmaxIndexPages_005fitems_005fisOffset_005findex_005fexport.get(com.jsptags.navigation.pager.PagerTag.class);
      boolean _jspx_th_pg_005fpager_005f0_reused = false;
      try {
        _jspx_th_pg_005fpager_005f0.setPageContext(_jspx_page_context);
        _jspx_th_pg_005fpager_005f0.setParent(null);
        // /public/page/pager.jsp(20,16) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pg_005fpager_005f0.setUrl(pagerURL);
        // /public/page/pager.jsp(20,16) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pg_005fpager_005f0.setItems(recordCount);
        // /public/page/pager.jsp(20,16) name = maxPageItems type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pg_005fpager_005f0.setMaxPageItems(maxPageItems);
        // /public/page/pager.jsp(20,16) name = maxIndexPages type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pg_005fpager_005f0.setMaxIndexPages(8);
        // /public/page/pager.jsp(20,16) name = isOffset type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pg_005fpager_005f0.setIsOffset(false);
        // /public/page/pager.jsp(20,16) name = index type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pg_005fpager_005f0.setIndex("center");
        // /public/page/pager.jsp(20,16) name = export type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pg_005fpager_005f0.setExport("offset,currentPageNumber=pageNumber");
        // /public/page/pager.jsp(20,16) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pg_005fpager_005f0.setScope("request");
        int _jspx_eval_pg_005fpager_005f0 = _jspx_th_pg_005fpager_005f0.doStartTag();
        if (_jspx_eval_pg_005fpager_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          java.lang.Integer offset = null;
          java.lang.Integer currentPageNumber = null;
          offset = (java.lang.Integer) _jspx_page_context.findAttribute("offset");
          currentPageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("currentPageNumber");
          do {
            out.write("\r\n                    ");

					if(paraArray!=null){
                    for(int pageParaIndex=0;pageParaIndex<paraArray.length;pageParaIndex++){
                    	if(pageParaIndex==0){
                    		pager_query_string.append("?");
                    	}else{
                    		pager_query_string.append("&");
                    	}
                    	if(request.getParameter(paraArray[pageParaIndex])!=null){
                    		pager_query_string.append(paraArray[pageParaIndex]).append("=").append(request.getParameter(paraArray[pageParaIndex]));
                    	}
                    	if(pager_query_string.toString().endsWith("&")){
                    	   pager_query_string = pager_query_string.deleteCharAt(pager_query_string.length()-1);
                    	}
                    
            out.write("\r\n                    ");
            //  pg:param
            com.jsptags.navigation.pager.ParamTag _jspx_th_pg_005fparam_005f0 = (com.jsptags.navigation.pager.ParamTag) _005fjspx_005ftagPool_005fpg_005fparam_0026_005fname_005fnobody.get(com.jsptags.navigation.pager.ParamTag.class);
            boolean _jspx_th_pg_005fparam_005f0_reused = false;
            try {
              _jspx_th_pg_005fparam_005f0.setPageContext(_jspx_page_context);
              _jspx_th_pg_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005fpager_005f0);
              // /public/page/pager.jsp(45,20) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_pg_005fparam_005f0.setName(paraArray[pageParaIndex]);
              int _jspx_eval_pg_005fparam_005f0 = _jspx_th_pg_005fparam_005f0.doStartTag();
              if (_jspx_th_pg_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fpg_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_pg_005fparam_005f0);
              _jspx_th_pg_005fparam_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fparam_005f0_reused);
            }
            out.write("\r\n                    ");
}
					}
            out.write("\r\n                    ");
            //  pg:index
            com.jsptags.navigation.pager.IndexTag _jspx_th_pg_005findex_005f0 = (com.jsptags.navigation.pager.IndexTag) _005fjspx_005ftagPool_005fpg_005findex_0026_005fexport.get(com.jsptags.navigation.pager.IndexTag.class);
            boolean _jspx_th_pg_005findex_005f0_reused = false;
            try {
              _jspx_th_pg_005findex_005f0.setPageContext(_jspx_page_context);
              _jspx_th_pg_005findex_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005fpager_005f0);
              // /public/page/pager.jsp(48,20) name = export type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_pg_005findex_005f0.setExport("pageCount,itemCount");
              int _jspx_eval_pg_005findex_005f0 = _jspx_th_pg_005findex_005f0.doStartTag();
              if (_jspx_eval_pg_005findex_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                java.lang.Integer itemCount = null;
                java.lang.Integer pageCount = null;
                itemCount = (java.lang.Integer) _jspx_page_context.findAttribute("itemCount");
                pageCount = (java.lang.Integer) _jspx_page_context.findAttribute("pageCount");
                do {
                  out.write("\r\n                    ");

                    if(request.getAttribute("pager.realCurrent")!=null){
                        currentPageNumber=new Integer(request.getAttribute("pager.realCurrent").toString());
                    }
                    if(maxPageItems!=recordCount){
                    
                  out.write("\r\n                    ");
                  //  pg:page
                  com.jsptags.navigation.pager.PageTag _jspx_th_pg_005fpage_005f0 = (com.jsptags.navigation.pager.PageTag) _005fjspx_005ftagPool_005fpg_005fpage.get(com.jsptags.navigation.pager.PageTag.class);
                  boolean _jspx_th_pg_005fpage_005f0_reused = false;
                  try {
                    _jspx_th_pg_005fpage_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_pg_005fpage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                    int _jspx_eval_pg_005fpage_005f0 = _jspx_th_pg_005fpage_005f0.doStartTag();
                    if (_jspx_eval_pg_005fpage_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      java.lang.String pageUrl = null;
                      java.lang.Integer pageNumber = null;
                      pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                      pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                      do {
                        out.write("\r\n                        ");

                        if(request.getAttribute("pager.realCurrent")!=null){
                            pageNumber=new Integer(request.getAttribute("pager.realCurrent").toString());
                        }
                        
                        out.print(com.js.lang.Resource.getValue(page_local,"common","comm.pager3"));
                        out.print(itemCount);
                        out.print(com.js.lang.Resource.getValue(page_local,"common","comm.pager4"));
                        out.write("\r\n                       ");
                        out.print(com.js.lang.Resource.getValue(page_local,"common","comm.pager1"));
                        out.write("<font color=\"red\">");
                        out.print(pageNumber);
                        out.write("</font>/");
                        out.print(pageCount);
                        out.print(com.js.lang.Resource.getValue(page_local,"common","comm.pager2"));
                        out.write("\r\n                       \r\n                    ");
                        int evalDoAfterBody = _jspx_th_pg_005fpage_005f0.doAfterBody();
                        pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                        pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                    }
                    if (_jspx_th_pg_005fpage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fpg_005fpage.reuse(_jspx_th_pg_005fpage_005f0);
                    _jspx_th_pg_005fpage_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fpage_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fpage_005f0_reused);
                  }
                  out.write("\r\n                    &nbsp;\r\n                    \r\n                     ");
                  //  pg:first
                  com.jsptags.navigation.pager.FirstTag _jspx_th_pg_005ffirst_005f0 = (com.jsptags.navigation.pager.FirstTag) _005fjspx_005ftagPool_005fpg_005ffirst.get(com.jsptags.navigation.pager.FirstTag.class);
                  boolean _jspx_th_pg_005ffirst_005f0_reused = false;
                  try {
                    _jspx_th_pg_005ffirst_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_pg_005ffirst_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                    int _jspx_eval_pg_005ffirst_005f0 = _jspx_th_pg_005ffirst_005f0.doStartTag();
                    if (_jspx_eval_pg_005ffirst_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      java.lang.String pageUrl = null;
                      java.lang.Integer pageNumber = null;
                      pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                      pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                      do {
                        out.write("\r\n                        ");
if(currentPageNumber.intValue()!=1){
                        out.write("\r\n                          <a href=\"");
                        out.print( pageUrl );
                        out.write("\"><img src=\"/jsoa/images/p_first.gif\" border=0 title=\"首页\"></a>\r\n                         ");
}else{
                        out.write("\r\n                         <img src=\"/jsoa/images/p_first2.gif\" border=0>\r\n                         ");
} 
                        out.write("\r\n                    ");
                        int evalDoAfterBody = _jspx_th_pg_005ffirst_005f0.doAfterBody();
                        pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                        pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                    }
                    if (_jspx_th_pg_005ffirst_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fpg_005ffirst.reuse(_jspx_th_pg_005ffirst_005f0);
                    _jspx_th_pg_005ffirst_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005ffirst_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005ffirst_005f0_reused);
                  }
                  out.write("\r\n                    ");
if(currentPageNumber.intValue()!=1){
                  out.write("\r\n                    ");
                  //  pg:prev
                  com.jsptags.navigation.pager.PrevTag _jspx_th_pg_005fprev_005f0 = (com.jsptags.navigation.pager.PrevTag) _005fjspx_005ftagPool_005fpg_005fprev.get(com.jsptags.navigation.pager.PrevTag.class);
                  boolean _jspx_th_pg_005fprev_005f0_reused = false;
                  try {
                    _jspx_th_pg_005fprev_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_pg_005fprev_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                    int _jspx_eval_pg_005fprev_005f0 = _jspx_th_pg_005fprev_005f0.doStartTag();
                    if (_jspx_eval_pg_005fprev_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      java.lang.String pageUrl = null;
                      java.lang.Integer pageNumber = null;
                      pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                      pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                      do {
                        out.write("\r\n                         <a href=\"");
                        out.print( pageUrl );
                        out.write("\"><img src=\"/jsoa/images/p_pre.gif\" border=0 title=\"上一页\"></a>\r\n                    ");
                        int evalDoAfterBody = _jspx_th_pg_005fprev_005f0.doAfterBody();
                        pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                        pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                    }
                    if (_jspx_th_pg_005fprev_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fpg_005fprev.reuse(_jspx_th_pg_005fprev_005f0);
                    _jspx_th_pg_005fprev_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fprev_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fprev_005f0_reused);
                  }
                  out.write("\r\n                    ");
}else{ 
                  out.write("\r\n                    <img src=\"/jsoa/images/p_pre2.gif\" border=0 >\r\n                    ");
} 
                  out.write("\r\n                    \r\n                   \r\n                    ");
                  //  pg:pages
                  com.jsptags.navigation.pager.PagesTag _jspx_th_pg_005fpages_005f0 = (com.jsptags.navigation.pager.PagesTag) _005fjspx_005ftagPool_005fpg_005fpages.get(com.jsptags.navigation.pager.PagesTag.class);
                  boolean _jspx_th_pg_005fpages_005f0_reused = false;
                  try {
                    _jspx_th_pg_005fpages_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_pg_005fpages_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                    int _jspx_eval_pg_005fpages_005f0 = _jspx_th_pg_005fpages_005f0.doStartTag();
                    if (_jspx_eval_pg_005fpages_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      java.lang.String pageUrl = null;
                      java.lang.Integer pageNumber = null;
                      if (_jspx_eval_pg_005fpages_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_pg_005fpages_005f0);
                      }
                      pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                      pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                      do {
                        out.write("\r\n                        ");

                        if (pageNumber.intValue() == currentPageNumber.intValue()) {
                        out.write("\r\n                        <span class=\"curPage\">");
                        out.print( pageNumber );
                        out.write("</span>\r\n                        ");
}else{
                        out.write("\r\n                        <a href=\"");
                        out.print( pageUrl );
                        out.write('"');
                        out.write('>');
                        out.print( pageNumber );
                        out.write("</a>\r\n                        ");
}
                        out.write("\r\n                    ");
                        int evalDoAfterBody = _jspx_th_pg_005fpages_005f0.doAfterBody();
                        pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                        pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                      if (_jspx_eval_pg_005fpages_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = _jspx_page_context.popBody();
                      }
                    }
                    if (_jspx_th_pg_005fpages_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fpg_005fpages.reuse(_jspx_th_pg_005fpages_005f0);
                    _jspx_th_pg_005fpages_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fpages_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fpages_005f0_reused);
                  }
                  out.write("\r\n                    ");
if(!currentPageNumber.equals(pageCount)){
                  out.write("\r\n                    ");
                  //  pg:next
                  com.jsptags.navigation.pager.NextTag _jspx_th_pg_005fnext_005f0 = (com.jsptags.navigation.pager.NextTag) _005fjspx_005ftagPool_005fpg_005fnext.get(com.jsptags.navigation.pager.NextTag.class);
                  boolean _jspx_th_pg_005fnext_005f0_reused = false;
                  try {
                    _jspx_th_pg_005fnext_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_pg_005fnext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                    int _jspx_eval_pg_005fnext_005f0 = _jspx_th_pg_005fnext_005f0.doStartTag();
                    if (_jspx_eval_pg_005fnext_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      java.lang.String pageUrl = null;
                      java.lang.Integer pageNumber = null;
                      pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                      pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                      do {
                        out.write("\r\n                         <a href=\"");
                        out.print( pageUrl );
                        out.write("\"><img src=\"/jsoa/images/p_next.gif\" border=0 title=\"下一页\"></a>\r\n                    ");
                        int evalDoAfterBody = _jspx_th_pg_005fnext_005f0.doAfterBody();
                        pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                        pageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("pageNumber");
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                    }
                    if (_jspx_th_pg_005fnext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fpg_005fnext.reuse(_jspx_th_pg_005fnext_005f0);
                    _jspx_th_pg_005fnext_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fnext_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fnext_005f0_reused);
                  }
                  out.write("\r\n                    ");
}else{ 
                  out.write("\r\n                    <img src=\"/jsoa/images/p_next2.gif\" border=0>\r\n                    ");
} 
                  out.write("\r\n                    \r\n                    ");
                  //  pg:last
                  com.jsptags.navigation.pager.LastTag _jspx_th_pg_005flast_005f0 = (com.jsptags.navigation.pager.LastTag) _005fjspx_005ftagPool_005fpg_005flast_0026_005fexport.get(com.jsptags.navigation.pager.LastTag.class);
                  boolean _jspx_th_pg_005flast_005f0_reused = false;
                  try {
                    _jspx_th_pg_005flast_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_pg_005flast_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pg_005findex_005f0);
                    // /public/page/pager.jsp(98,20) name = export type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_pg_005flast_005f0.setExport("pageUrl");
                    int _jspx_eval_pg_005flast_005f0 = _jspx_th_pg_005flast_005f0.doStartTag();
                    if (_jspx_eval_pg_005flast_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      java.lang.String pageUrl = null;
                      pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                      do {
                        out.write("\r\n                        ");
if(!currentPageNumber.equals(pageCount)){
                        out.write("\r\n                         <a href=\"");
                        out.print( pageUrl );
                        out.write("\"><img src=\"/jsoa/images/p_last.gif\" border=0 title=\"尾页\"></a>\r\n                         ");
}else{
                        out.write("\r\n                         <img src=\"/jsoa/images/p_last2.gif\" border=0>\r\n                         ");
} 
                        out.write("\r\n                    ");
                        int evalDoAfterBody = _jspx_th_pg_005flast_005f0.doAfterBody();
                        pageUrl = (java.lang.String) _jspx_page_context.findAttribute("pageUrl");
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                    }
                    if (_jspx_th_pg_005flast_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fpg_005flast_0026_005fexport.reuse(_jspx_th_pg_005flast_005f0);
                    _jspx_th_pg_005flast_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005flast_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005flast_005f0_reused);
                  }
                  out.write("\r\n                    \r\n                    \r\n                    ");
}
                  out.write("\r\n                    ");
                  int evalDoAfterBody = _jspx_th_pg_005findex_005f0.doAfterBody();
                  itemCount = (java.lang.Integer) _jspx_page_context.findAttribute("itemCount");
                  pageCount = (java.lang.Integer) _jspx_page_context.findAttribute("pageCount");
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_pg_005findex_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fpg_005findex_0026_005fexport.reuse(_jspx_th_pg_005findex_005f0);
              _jspx_th_pg_005findex_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005findex_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005findex_005f0_reused);
            }
            out.write("\r\n                    ");
            int evalDoAfterBody = _jspx_th_pg_005fpager_005f0.doAfterBody();
            offset = (java.lang.Integer) _jspx_page_context.findAttribute("offset");
            currentPageNumber = (java.lang.Integer) _jspx_page_context.findAttribute("currentPageNumber");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_pg_005fpager_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fpg_005fpager_0026_005furl_005fscope_005fmaxPageItems_005fmaxIndexPages_005fitems_005fisOffset_005findex_005fexport.reuse(_jspx_th_pg_005fpager_005f0);
        _jspx_th_pg_005fpager_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pg_005fpager_005f0, _jsp_getInstanceManager(), _jspx_th_pg_005fpager_005f0_reused);
      }
      out.write("\t\t\t\t\t\r\n\t\t\t\t\t&nbsp;第&nbsp;<input id=\"inputPageNum\" type=\"text\" style=\"height:18px;\" name=\"page_jump_num\" size=3 onKeyUp=\"this.value=this.value.replace(/\\D/g,'')\" onafterpaste=\"this.value=this.value.replace(/\\D/g,'')\">&nbsp;页&nbsp;<input type=\"button\" class=\"btnButton4Font\" style=\"height:18px;margin-bottom:7px;\" value=\"Go\" onclick=\"page_go_jump()\"></input>\r\n\t\t\t\t\t");
}
      out.write("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</table>\r\n</div>\r\n\r\n<script language =\"javascript\">\r\nfunction page_go_jump(){\r\n   var pageNum=document.getElementById(\"inputPageNum\").value;\r\n   if(!parseInt(pageNum,10)>0)\r\n   {\r\n   \t\talert(\"请输入正确的页码!\");\r\n   \t\tdocument.getElementById(\"inputPageNum\").value=\"\";\r\n   \t\treturn;\r\n   }\r\n   var num=document.all.page_jump_num.value;\r\n   if(checkNUM(num)==0)num=0;\r\n   var recordCount=");
      out.print(recordCount);
      out.write(";\r\n   var maxPageItems=");
      out.print(maxPageItems);
      out.write(";\r\n   \r\n   var maxPageNum=parseInt((recordCount/maxPageItems))+1;\r\n   \r\n   if(num>maxPageNum){\r\n      num=(maxPageNum-1)*15;\r\n   }else{\r\n      num=(num-1)*15;\r\n   }\r\n   location.href=\"");
      out.print(pager_query_string.toString());
      out.write("&pager.offset=\"+num;\r\n}\r\n\r\nfunction checkNUM(NUM)\r\n{\r\n\tvar i,j,strTemp;\r\n\tstrTemp=\"0123456789\";\r\n\tif ( NUM.length== 0)\r\n\t\treturn 0\r\n\tfor (i=0;i<NUM.length;i++)\r\n\t{\r\n\t\tj=strTemp.indexOf(NUM.charAt(i));\r\n\t\tif (j==-1)\r\n\t\t{\r\n\t\t\t//说明有字符不是数字\r\n\t\t\treturn 0;\r\n\t\t}\r\n\t}\r\n\t//说明是数字\r\n\treturn 1;\r\n}\r\n</script>\r\n");
      out.write("\r\n\t</td>\r\n  </tr>  \r\n</table>\r\n</td>\r\n</tr>\r\n</table>\r\n<table id=\"bartable\" width=\"100%\" height=\"100%\" border=0 ");
if(!"1".equals(caculating)){out.print("style=\"display:none\"");} 
      out.write(">\r\n  <tr width=\"100%\" height=\"100%\">\r\n  \t<td align=\"center\" valign=\"middle\" width=\"100%\" height=\"100%\">\r\n  \t   考勤汇总正在计算中，请耐心等待......<br><br>\r\n  \t   <IMG SRC=\"/jsoa/iSignatureHTML.jsp/load.gif\" />\r\n  \t   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>\r\n  \t   \r\n  \t    \r\n  \t</td>\r\n  </tr>\r\n</table>\r\n</body>\r\n</html>\r\n<script language=\"javascript\">\r\nfunction exportList(){\r\n\tvar month=document.getElementById(\"currentMonth\").value;\r\n\tvar userName=document.getElementById(\"userName\").value;\r\n\tvar searchOrgId=document.getElementById(\"searchOrgId\").value;\r\n\t\r\n\tJSMainWinOpen(\"/jsoa/SKqReportAction.do?action=export&currentMonth=\"+month+\"&userName=\"+userName+\"&searchOrgId=\"+searchOrgId);\r\n}\r\nfunction reCaculate(){\r\n\t\r\n\tdocument.getElementById(\"listtable\").style.display=\"none\";\t\r\n\tdocument.getElementById(\"bartable\").style.display=\"\";\t\r\n\tvar month=document.getElementById(\"currentMonth\").value;\r\n\tvar url=\"/jsoa/SKqReportAction.do?action=caculate&currentMonth=\"+month+\"&sdate=\"+new Date();\t\r\n\tdocument.getElementById(\"myIframe\").src=url;\t\r\n");
      out.write("}\r\nfunction dataLock(){\r\n\tlocation.href=\"/jsoa/SKqReportAction.do?action=list&dataLock=1&currentMonth=");
      out.print(currentMonth);
      out.write("\";\t\r\n}\r\nfunction searcher(){\r\n\tdocument.frm1.submit();\r\n}\r\nfunction unsearcher(){\r\n\tlocation.href=\"/jsoa/SKqReportAction.do?action=list\";\r\n}\r\nfunction hidserch(){\r\n     var stable=document.getElementById(\"searchtable\");\r\n     var sbutton=document.getElementById(\"hiddenSearch\");\r\n     if(stable.style.display==\"none\"){\r\n\t      stable.style.display=\"\";\r\n\t      document.getElementById(\"hiddenSearch1\").value=\"关闭查询\";\r\n     }else{\r\n\t     stable.style.display=\"none\";\r\n\t     document.getElementById(\"hiddenSearch1\").value=\"查询\";\r\n     }\r\n}\r\nfunction goMonth(month){\r\n\tlocation.href=\"/jsoa/SKqReportAction.do?action=list&currentMonth=\"+month;\r\n}\r\nfunction selectEndowOrg(contrId,contrName,type,single,show,range){\r\n    var selectedId=eval(\"document.all.\"+contrId+\".value\");\r\n    var selectedName=eval(\"document.all.\"+contrName+\".value\");\r\n    if(selectedId==null || selectedId==\"null\" || selectedId==\"\"){\r\n        selectedId=\"\";\r\n        selectedName=\"\";\r\n    }\r\n    selectPersionFromOrg('','searchOrgId','searchOrgName',selectedId,selectedName,'orgPerson','','root',range,'noonly','org');\r\n");
      out.write("}\r\n</script>\r\n<script src=\"/jsoa/js/util.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
