/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2023-01-06 10:07:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsflow;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.js.lang.Resource;

public final class wf_005ftranread_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tag-lib/struts-bean.tld", Long.valueOf(1499751390000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.js.lang.Resource");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n");

String local = session.getAttribute("org.apache.struts.action.LOCALE").toString();

      out.write('\r');
      out.write('\n');

//参数信息
String submitPersonId = request.getParameter("submitPersonId");
String moduleId = request.getParameter("moduleId");
String processId = request.getParameter("processId");
String tableId = request.getParameter("tableId");
String recordId = request.getParameter("recordId");
String curActivityId = request.getParameter("activityId");//当前活动
String activityId = "0";//用户选择的活动后继
String msgFrom = request.getParameter("msgFrom");

//显示短信
boolean showSmsRemind = false;
if(new com.js.oa.message.action.ModelSendMsg().judgePurviewMessage(msgFrom,session.getAttribute("domainId")==null?"0":session.getAttribute("domainId").toString())){
	if(new com.js.system.manager.service.ManagerService().hasRight(session.getAttribute("userId").toString(), "09*01*01")){
		showSmsRemind = true;
	}
}


      out.write("\r\n<head>\r\n\r\n<title>转阅</title>\r\n<link href=\"/jsoa/skin/");
      out.print(session.getAttribute("skin"));
      out.write("/style-");
      out.print(session.getAttribute("browserVersion"));
      out.write(".css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<script src=\"/jsoa/js/js.js\" language=\"javascript\"></script>\r\n<SCRIPT language=\"javascript\" src=\"/jsoa/js/openEndow.js\"></SCRIPT>\r\n<META HTTP-EQUIV=\"pragma\" CONTENT=\"no-cache\">\r\n<META HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache\">\r\n<META HTTP-EQUIV=\"expires\" CONTENT=\"0\">\r\n</head>\r\n<base target=_self>\r\n<body leftmargin=\"0\" topmargin=\"0\" onload=\"resizeWin(530,500);\">\r\n<form name=\"frm1\" id=\"frm1\" style=\"margin:0px;\">\r\n<table  border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"pup_main\">\r\n<tr style=\"display:none\">\r\n    <td id=\"pup_top\"><table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n      <tr>\r\n        <td><div id=\"pup_topright\"></div></td>\r\n        <td id=\"pup_topleft\">&nbsp;</td>\r\n      </tr>\r\n    </table></td>\r\n</tr>\r\n<tr>\r\n\t<td align=\"center\" valign=\"top\">\r\n\t<div id=\"pup_content\">\r\n\r\n\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"3\" cellspacing=\"0\" style=\"margin:0px;border:0px;\">\r\n\t  <tr id=\"stepTR\" style=\"display:none\">\r\n\t    <td colspan=\"3\">\r\n");
      out.write("\t     <table border=\"0\" width=\"100%\" height=\"100%\"  cellpadding=\"0\" cellspacing=\"0\" style=\"margin:0px;border:0px;\">\r\n\t\t  <tr>\r\n\t\t  <td width=\"80\" height=\"50\" valign=\"top\" nowrap>");
      if (_jspx_meth_bean_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("：<font color=\"red\">*</font></td>\r\n\t\t  <td align=\"left\">\r\n\t\t  <div><INPUT TYPE=\"radio\" NAME=\"step\" style=\"display:none\"></div>\r\n\t\t  </td>\r\n\t      </tr>\r\n\t\t  </table>\r\n\t   </td>\r\n\t  </tr>\r\n\t  <tr id=\"approveTR\" style=\"display:none\">\r\n\t    <td colspan=\"3\">\r\n\t     <table border=\"0\" width=\"100%\" height=\"100%\"  cellpadding=\"0\" cellspacing=\"0\" style=\"margin:0px;border:0px;\">\r\n\t\t <tr>\r\n\t\t\t<td width=\"80\" nowrap>");
      if (_jspx_meth_bean_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("：<font color=\"red\">*</font></td>\r\n\t\t\t<td align=\"left\">\r\n\t\t\t\t<span id=\"approveMode\" name=\"approveMode\" style=\"display:none\"><INPUT TYPE=\"radio\" NAME=\"approve\" value=\"2\">");
      if (_jspx_meth_bean_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("</span><!--2-->\r\n\t\t\t\t<span id=\"approveMode\" name=\"approveMode\" style=\"display:none\"><INPUT TYPE=\"radio\" NAME=\"approve\" value=\"0\">");
      if (_jspx_meth_bean_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("</span><!--0-->\r\n\t\t\t\t<span id=\"approveMode\" name=\"approveMode\" style=\"display:none\"><INPUT TYPE=\"radio\" NAME=\"approve\" value=\"1\">");
      if (_jspx_meth_bean_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("</span><!--1-->\r\n\t\t\t\t<span id=\"approveMode\" name=\"approveMode\" style=\"display:none\"><INPUT TYPE=\"radio\" NAME=\"approve\" value=\"3\">");
      if (_jspx_meth_bean_005fmessage_005f5(_jspx_page_context))
        return;
      out.write("</span><!--3-->\r\n\t\t   </td>\r\n\t      </tr>\r\n\t\t  </table>\r\n\t   </td>\r\n\t  </tr>\r\n\r\n\t  <tr style=\"display:none\">\r\n\t\t  <!--环节名称-->\r\n\t\t<td width=\"45%\" height=\"20\"><select name=\"stepName\" size=\"1\" style=\"width:100%;\" onchange=\"changeActivity(this.value);\">\r\n\t\t\t</select>\r\n\t\t</td>\r\n\t\t<td width=\"10%\" height=\"20\">&nbsp;</td>\r\n\t\t<!--审批方式-->\r\n\t\t<td width=\"45%\" height=\"20\"><select name=\"approveMode\" size=\"1\" style=\"width:100%;\">\r\n\t\t</select></td>\r\n\t  </tr>\r\n\t  <tr id=\"middleTR\">\r\n\t\t<td valign=\"top\" width=\"45%\"><iframe id=\"orgifm\" name=\"orgifm\" frameborder=\"1\" scrolling=\"auto\" width=\"100%\" height=\"100%\" src='/jsoa/jsflow/wf_tranread_org.jsp?curActivityId=");
      out.print(curActivityId);
      out.write("&processId=");
      out.print(processId);
      out.write("&tableId=");
      out.print(tableId);
      out.write("&recordId=");
      out.print(recordId);
      out.write("&submitPersonId=");
      out.print(submitPersonId);
      out.write("&activityId=");
      out.print(curActivityId);
      out.write("'></iframe></td>\r\n\t\t<td align=\"center\" width=\"10%\">\r\n\t\t<input type=\"button\" name=\"Submit4\" value=\"<&nbsp;\" class=\"btnButton4font\" style=\"margin-top:10px;margin-bottom:10px;\" onclick=\"delOptions();\"/>\r\n\t\t<input type=\"button\" name=\"Submit5\" value=\"<<\" class=\"btnButton4font\" style=\"margin-top:10px;margin-bottom:10px;\" onclick=\"delAllOptions();\"/>\r\n\t\t</td>\r\n\t\t<td valign=\"top\" width=\"45%\"><select name=\"selectObject\" id=\"selectObject\" size=\"10\" ondblclick=\"delOptions();\" multiple=\"multiple\" style=\"width:100%;height:100%;\">\r\n\r\n\t\t  </select>\r\n\t\t</td>\r\n\t  </tr>\r\n\r\n\t  <tr id=\"selTextarea\"  style=\"display:none\">\r\n\t    <td colspan=\"3\">\r\n\t     <table border=\"0\" width=\"100%\" height=\"100%\"  cellpadding=\"0\" cellspacing=\"0\" style=\"margin:0px;border:0px;\">\r\n\t\t   <tr id=\"selTextareaTag\">\r\n\t\t\t<td height=\"4\">");
      out.print(Resource.getValue(local,"filetransact","file.people"));
      out.write("：&nbsp;&nbsp;<button class=\"btnButton5font\" onclick=\"javascript:openSelUserWIN();\">");
      out.print(Resource.getValue(local,"filetransact","file.selectran"));
      out.write("</button></td>\r\n\t\t\t<td height=\"4\">&nbsp;</td>\r\n\t\t  </tr>\r\n\t\t   <tr>\r\n\t\t\t <td style=\"width:100%;\">\r\n\t\t\t\t<textarea name=\"selectedTxt\" rows=\"12\" cols=\"100\" class=\"inputTextarea\" readonly=\"true\" style=\"width:100%;heigh:100%\" ></textarea>\r\n\t\t\t </td>\r\n\t\t\t <td id=\"selTextareaTagOld\" style=\"display='none'\" valign=\"bottom\" align=\"left\"><img width=\"15\" height=\"16\" border=\"0\" src=\"/jsoa/images/select.gif\" style=\"cursor:pointer\" onClick=\"openSelUserWIN();\">\r\n\t\t\t <input type=\"hidden\" name=\"selectedTxtId\">\r\n\t\t\t <input type=\"hidden\" name=\"selRange\">\r\n\t\t\t <input type=\"hidden\" name=\"participantType\" value=\"-1\">\r\n\t\t\t <input type=\"hidden\" name=\"tranType\" value=\"-1\">\r\n\t\t\t </td>\r\n\t\t   </tr>\r\n\t\t </table>\r\n\t\t</td>\r\n\t  </tr>\r\n\r\n\t  <tr>\r\n\t\t<td height=\"30\" colspan=\"3\">\r\n\t\t<table border=\"0\" width=\"100%\" height=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:0px;\">\r\n\t\t  <tr>\r\n\t\t\t\t");

				String message = "none";//是否显示短信
				if(showSmsRemind){
					message = "";
				}
				
      out.write("\r\n\r\n\t\t\t<td style=\"display:");
      out.print(message);
      out.write("\" id=\"smsTD\">\r\n\t\t\t\t<INPUT TYPE=\"hidden\" name=\"showSmsRemind\" value=\"");
      out.print(showSmsRemind);
      out.write("\">\r\n\t\t\t\t<span id=\"smsDiv\">\r\n\t\t\t\t\t<input type=\"checkbox\" id=\"r1\" name=\"needSendMsg\" onclick=\"showSmsContentHref();\"/>\r\n\t\t\t\t\t<label for=\"r1\">");
      out.print(Resource.getValue(local,"filetransact","file.messageremind"));
      out.write("</label>\r\n\t\t\t\t\t<label id=\"smsHrefLabel\"><A HREF=\"javascript:\" onclick=\"showSmsContent();\">");
      out.print(Resource.getValue(local,"filetransact","file.smsremindcontent"));
      out.write("</A></label>\r\n\t\t\t\t</span>\r\n\t\t\t</td>\r\n\t\t  </tr>\r\n\t    </table>\r\n\t\t</td>\r\n\t </tr>\r\n\t <tr id=\"smsContentTR\"  style=\"display:none\">\r\n\t    <td colspan=\"3\">\r\n\t     <table border=\"0\" width=\"100%\" height=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:0px;border:0px;\">\r\n\t\t  <tr>\r\n\t\t\t <td style=\"width:100%;\">\r\n\t\t\t\t<textarea name=\"smsContent\" rows=\"4\" cols=\"100\" class=\"inputTextarea\" style=\"width:100%;heigh:100%\">");
      out.print(request.getAttribute("smsContent")+"");
      out.write("</textarea>\t\t\t \r\n\t\t\t </td>\r\n\t\t   </tr>\r\n\t\t </table>\t\t\r\n\t\t </td>\r\n\t  </tr>\r\n\r\n\t </table>\r\n\t</div>\r\n\r\n\t  <tr>\r\n\t\t<td valign=\"top\" align=\"right\"> \r\n\t\t\t<input type=\"button\" name=\"Submit\" value=\"");
      if (_jspx_meth_bean_005fmessage_005f6(_jspx_page_context))
        return;
      out.write("\" class=\"btnButton2font\" onclick=\"include_save();\"/>\r\n\t\t\t<input type=\"button\" name=\"Cancel\" value=\"");
      if (_jspx_meth_bean_005fmessage_005f7(_jspx_page_context))
        return;
      out.write("\" class=\"btnButton2font\" onclick=\"window.close();\" />\r\n\t\t\t&nbsp;&nbsp;\r\n\t\t</td>\r\n\t  </tr>\r\n  </table>\r\n\t</form>\r\n</body>\r\n</html>\r\n<SCRIPT LANGUAGE=\"JavaScript\">\r\n<!--\r\n\r\n//显示短信内容\r\nfunction showSmsContent(){\r\n\tif(document.all.smsContentTR.style.display==\"none\"){\r\n\t\tdocument.all.smsContentTR.style.display = \"\";\r\n\t} else{\r\n\t\tdocument.all.smsContentTR.style.display = \"none\";\r\n\t}\r\n}\r\n\r\n//显示短信内容链接\r\nfunction showSmsContentHref(){\r\n\tif(document.all.r1.checked){\r\n\t\tdocument.all.smsHrefLabel.style.display = \"\";\r\n\t} else{\r\n\t\tdocument.all.smsHrefLabel.style.display = \"none\";\r\n\t\tdocument.all.smsContentTR.style.display = \"none\";\r\n\t}\r\n}\r\n\r\n\r\nfunction delOptions(){\r\n\tvar oSelect=document.all.selectObject;\r\n\tvar nLen =oSelect.length;\r\n\tvar sel;\r\n\tfor(i=0;i<nLen;i++){\r\n\t\tvar optObj = oSelect.options(i);\r\n\t\tif(optObj.selected){\r\n\t\t\tsel = i;\r\n\t\t}\r\n\t}\r\n\t//删除\r\n\tif(sel != null){\r\n\t\toSelect.remove(sel);\r\n\t} else{\r\n\t\talert(\"");
      out.print(Resource.getValue(local,"filetransact","file.selectdeleteperson"));
      out.write("\");\r\n\t}\r\n}\r\n\r\nfunction delAllOptions(){\r\n\tvar oSelect=document.all.selectObject;\r\n\tvar nLen =oSelect.length;\r\n\tfor(j=0;j<nLen;j++){\r\n\t\t//删除\r\n\t\toSelect.remove(0);\r\n\t}\r\n}\r\n\r\n\r\nfunction openSelUserWIN(){\r\n\tvar type=document.all.participantType.value;\r\n\tvar range = document.all.selRange.value;\r\n\tif(type==\"12\"){\r\n\t\ttype=\"org\";\r\n\t}else if(type==\"8\"){\r\n\t\tif(range != null && range!=\"\" && range.indexOf(\"@\") < 0 && range.indexOf(\"*\") < 0){\r\n\t\t\ttype = \"user\";\r\n\t\t}else if(range != null && range!=\"\" && range.indexOf(\"@\") < 0){\r\n\t\t\ttype = \"userorg\";\r\n\t\t}else if(range != null && range!=\"\" && range.indexOf(\"*\") < 0){\r\n\t\t\ttype = \"usergroup\";\r\n\t\t} else{\r\n\t\t\ttype = \"usergrouporg\";\r\n\t\t}\r\n\t} else if(type==\"13\"){\r\n\t\ttype = \"usergroup\";\r\n\t} else if(type<0){\r\n\t\ttype = \"user\";\r\n\t} else{\r\n\t\ttype=\"usergroup\";\r\n\t}\r\n\topenEndow('selectedTxtId','selectedTxt',document.all.selectedTxtId.value,document.all.selectedTxt.value,type,'no',type,document.all.selRange.value)\r\n}\r\n\r\n\r\n//保存\r\nfunction include_save(){\r\n\tvar participantType=document.all.participantType.value;\r\n");
      out.write("\tvar tranType=document.all.tranType.value;\r\n\r\n\t//var oo = new Object();\r\n\r\n\t//短信\r\n\tif(document.all.smsDiv.style.display=\"\"){\r\n\t\tif(document.frm1.needSendMsg && document.frm1.needSendMsg.checked){\r\n\t\t\twindow.opener.document.all.needSendMsg.value=document.frm1.needSendMsg.checked;//短信\r\n\t\t\twindow.opener.document.all.smsContent.value=document.frm1.smsContent.value;//短信\r\n\t\t}\r\n\t}\r\n\r\n\twindow.opener.document.all.operId.value = '';\r\n\twindow.opener.document.all.operName.value = '';\r\n\r\n\tif(tranType==\"0\" || tranType==\"1\" || tranType==\"2\" || tranType==\"4\" || participantType==\"1\" || participantType==\"8\" || participantType==\"2\" || participantType==\"9\" || participantType==\"10\" || participantType==\"6\" || participantType==\"13\" || participantType==\"0\" || participantType==\"7\" || participantType==\"11\"){\r\n\t\tvar oSelect=document.all.selectObject;\r\n\t\tvar nLen =oSelect.length;\r\n\t\tfor(i=0;i<nLen;i++){\r\n\t\t\twindow.opener.document.all.operId.value += oSelect.options[i].value ;\r\n\t\t\twindow.opener.document.all.operName.value += oSelect.options[i].text + \",\";\r\n");
      out.write("\t\t}\r\n\t\tif(participantType==\"10\"){\r\n\t\t\twindow.opener.document.all.mainPassRoundUserType.value = \"10\";\r\n\t\t}\r\n\t}else{\r\n\t\twindow.opener.document.all.operId.value=document.all.selectedTxtId.value;\r\n\t\twindow.opener.document.all.operName.value=document.all.selectedTxt.value;\r\n\t}\r\n\r\n\r\n\tif(window.opener.document.all.operName.value.indexOf(\",\",window.opener.document.all.operName.value.length-1)!=-1){\r\n\t\twindow.opener.document.all.operName.value = window.opener.document.all.operName.value.substring(0,window.opener.document.all.operName.value.length-1);\r\n\t}\t\r\n\t\r\n\twindow.close();\r\n\r\n\t//转发阅件\r\n\twindow.opener.include_selfsendSubmit('transRead');\r\n\t//分发阅件\r\n\tvar userAgent=navigator.userAgent;\r\n\tvar isEdge = userAgent.indexOf(\"Edge\") > -1; //判断是否IE的Edge浏览器\r\n\tif(isEdge){\r\n\t\twindow.opener.include_selfsendSubmit('transRead');\r\n\t\twindow.close();\r\n\t\talert(\"");
      out.print(Resource.getValue(local,"workflow","workflow.includehassuccessturn"));
      out.write("\"+(window.opener.document.all.operName.value==''?\"\":(\"");
      out.print(Resource.getValue(local,"workflow","workflow.includeto"));
      out.write("\"+window.opener.document.all.operName.value))+(window.opener.document.all.mainPassRoundUserType.value=='10'?\"");
      out.print(Resource.getValue(local,"workflow","workflow.includeleader"));
      out.write("\":\"\")+\"！\");\r\n\t}else{\r\n\t\twindow.close();\r\n\t\twindow.opener.include_selfsendSubmit('transRead');\r\n\t}\r\n}\r\n//-->\r\n</SCRIPT>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_bean_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f0 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    boolean _jspx_th_bean_005fmessage_005f0_reused = false;
    try {
      _jspx_th_bean_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fmessage_005f0.setParent(null);
      // /jsflow/wf_tranread.jsp(58,51) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f0.setBundle("filetransact");
      // /jsflow/wf_tranread.jsp(58,51) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f0.setKey("file.nextactivity");
      int _jspx_eval_bean_005fmessage_005f0 = _jspx_th_bean_005fmessage_005f0.doStartTag();
      if (_jspx_th_bean_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
      _jspx_th_bean_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f1 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    boolean _jspx_th_bean_005fmessage_005f1_reused = false;
    try {
      _jspx_th_bean_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fmessage_005f1.setParent(null);
      // /jsflow/wf_tranread.jsp(70,25) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f1.setBundle("filetransact");
      // /jsflow/wf_tranread.jsp(70,25) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f1.setKey("file.auditype");
      int _jspx_eval_bean_005fmessage_005f1 = _jspx_th_bean_005fmessage_005f1.doStartTag();
      if (_jspx_th_bean_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f1);
      _jspx_th_bean_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f2 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    boolean _jspx_th_bean_005fmessage_005f2_reused = false;
    try {
      _jspx_th_bean_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fmessage_005f2.setParent(null);
      // /jsflow/wf_tranread.jsp(72,112) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f2.setBundle("workflow");
      // /jsflow/wf_tranread.jsp(72,112) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f2.setKey("workflow.newactivitysingletype");
      int _jspx_eval_bean_005fmessage_005f2 = _jspx_th_bean_005fmessage_005f2.doStartTag();
      if (_jspx_th_bean_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f2);
      _jspx_th_bean_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f3 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    boolean _jspx_th_bean_005fmessage_005f3_reused = false;
    try {
      _jspx_th_bean_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fmessage_005f3.setParent(null);
      // /jsflow/wf_tranread.jsp(73,112) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f3.setBundle("workflow");
      // /jsflow/wf_tranread.jsp(73,112) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f3.setKey("workflow.newactivitysinglemul");
      int _jspx_eval_bean_005fmessage_005f3 = _jspx_th_bean_005fmessage_005f3.doStartTag();
      if (_jspx_th_bean_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f3);
      _jspx_th_bean_005fmessage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f4 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    boolean _jspx_th_bean_005fmessage_005f4_reused = false;
    try {
      _jspx_th_bean_005fmessage_005f4.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fmessage_005f4.setParent(null);
      // /jsflow/wf_tranread.jsp(74,112) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f4.setBundle("workflow");
      // /jsflow/wf_tranread.jsp(74,112) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f4.setKey("workflow.newactivitymulcollateral");
      int _jspx_eval_bean_005fmessage_005f4 = _jspx_th_bean_005fmessage_005f4.doStartTag();
      if (_jspx_th_bean_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f4);
      _jspx_th_bean_005fmessage_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f5 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    boolean _jspx_th_bean_005fmessage_005f5_reused = false;
    try {
      _jspx_th_bean_005fmessage_005f5.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fmessage_005f5.setParent(null);
      // /jsflow/wf_tranread.jsp(75,112) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f5.setBundle("workflow");
      // /jsflow/wf_tranread.jsp(75,112) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f5.setKey("workflow.newactivitymul");
      int _jspx_eval_bean_005fmessage_005f5 = _jspx_th_bean_005fmessage_005f5.doStartTag();
      if (_jspx_th_bean_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f5);
      _jspx_th_bean_005fmessage_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f5, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f6 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    boolean _jspx_th_bean_005fmessage_005f6_reused = false;
    try {
      _jspx_th_bean_005fmessage_005f6.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fmessage_005f6.setParent(null);
      // /jsflow/wf_tranread.jsp(166,45) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f6.setBundle("common");
      // /jsflow/wf_tranread.jsp(166,45) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f6.setKey("comm.confirm");
      int _jspx_eval_bean_005fmessage_005f6 = _jspx_th_bean_005fmessage_005f6.doStartTag();
      if (_jspx_th_bean_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f6);
      _jspx_th_bean_005fmessage_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f6, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f7 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    boolean _jspx_th_bean_005fmessage_005f7_reused = false;
    try {
      _jspx_th_bean_005fmessage_005f7.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fmessage_005f7.setParent(null);
      // /jsflow/wf_tranread.jsp(167,45) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f7.setBundle("common");
      // /jsflow/wf_tranread.jsp(167,45) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f7.setKey("comm.cancel");
      int _jspx_eval_bean_005fmessage_005f7 = _jspx_th_bean_005fmessage_005f7.doStartTag();
      if (_jspx_th_bean_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f7);
      _jspx_th_bean_005fmessage_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f7, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f7_reused);
    }
    return false;
  }
}
